In [106]:
# candidate_parser
# career_extractor
# jd_parser
# embedding_engine
# career_match_engine
# signal_engine
# ranker
# explainer
# role_engine

In [220]:
import os
print(os.getcwd())

import sys
print(sys.path[:5])

import sys
sys.path.insert(0, r"D:\India Runs\TalentDNA_AI")

d:\India Runs\TalentDNA_AI\notebooks
['D:\\India Runs\\TalentDNA_AI', 'D:\\India Runs\\TalentDNA_AI', 'D:\\India Runs\\TalentDNA_AI', 'C:\\Users\\vinit\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip', 'C:\\Users\\vinit\\AppData\\Local\\Programs\\Python\\Python311\\DLLs']

In [221]:
import pandas as pd
import numpy as np

from src.parser import CandidateParser
from src.career_features import CareerFeatureExtractor
from src.jd_parser import JDParser

from src.embeddings import EmbeddingEngine
from src.career_match import CareerMatchEngine
from src.signals import SignalEngine
from src.ranker import HybridRanker
from src.explainability import ExplainabilityEngine

In [222]:
candidate_parser = CandidateParser()
career_extractor = CareerFeatureExtractor()
jd_parser = JDParser()
embedding_engine = EmbeddingEngine()
career_match_engine = CareerMatchEngine()
signal_engine = SignalEngine()
ranker = HybridRanker()
explainer = ExplainabilityEngine()
print("ALL MODULES LOADED")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

ALL MODULES LOADED

In [223]:
import pandas as pd
df = pd.read_json(
    r"D:\India Runs\TalentDNA_AI\data\raw\candidates.jsonl",
    lines=True
)

In [225]:
print(df.shape)

(100000, 8)

In [226]:
jd_text = """Job Description: Senior AI Engineer — Founding TeamCompany: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineering org from scratch. This is the kind of role where the JD changes every six months because the company changes every six months. So instead of pretending we have a fixed checklist, we're going to tell you what we actually need and what we've gotten wrong before.
If you've spent your career at Google or Meta and you want a well-scoped role with a defined ladder, this isn't it.
If you've spent your career bouncing between early-stage startups and you want to "just code" without having to think about product or recruiter workflows or eval frameworks, this also isn't it.
We need someone who is simultaneously comfortable with two things that sound contradictory:
1.	Deep technical depth in modern ML systems — embeddings, retrieval, ranking, LLMs, fine-tuning.
2.	Scrappy product-engineering attitude — willing to ship a working ranker in a week even if the underlying ML is "obviously suboptimal," because we need to learn from real users before we know what to actually optimize for.
These are not contradictory in real life. They feel contradictory because of how engineering culture sorted itself into "researcher" vs "shipper" archetypes. We need both modes available in the same person, and we'd rather you tilt slightly toward shipper than toward researcher.

What you'd actually be doing
The high-level mandate: own the intelligence layer of Redrob's product. That means the ranking, retrieval, and matching systems that decide what recruiters see when they search for candidates and what candidates see when they search for roles.
In practical terms, your first 90 days will probably look like:
•	Weeks 1-3: Audit what we currently have (it's mostly BM25 + rule-based scoring, working but not great). Identify the 3-4 highest-leverage things to fix.
•	Weeks 4-8: Ship a v2 ranking system that demonstrably improves recruiter-engagement metrics. This will involve embeddings, hybrid retrieval, and probably some LLM-based re-ranking, but the architecture is your call.
•	Weeks 9-12: Set up the evaluation infrastructure — offline benchmarks, online A/B testing, recruiter-feedback loops — so we can keep improving without flying blind.
Beyond that, you'll be driving the long-term architecture of how we do candidate-JD matching at scale, mentoring the next round of hires (we're growing the team from 4 to 12 engineers in the next year), and working closely with our recruiter-experience PM on what to build.

What we mean by "5-9 years"
This is a range, not a requirement. Some people hit "senior engineer" judgment at 4 years; some never hit it after 15. We've used 5-9 because it's roughly where people we've hired into this kind of role have landed, but we'll seriously consider candidates outside the band if other signals are strong.
That said, here are the disqualifiers we actually apply:
•	If you've spent your career in pure research environments (academic labs, research-only roles) without any production deployment — we will not move forward. We are explicit about this. We've tried it twice and it didn't work for either side.
•	If your "AI experience" consists primarily of recent (under 12 months) projects using LangChain to call OpenAI — we will probably not move forward, unless you can demonstrate substantial pre-LLM-era ML production experience. We're looking for people who understood retrieval and ranking before it became fashionable.
•	If you are a senior engineer who hasn't written production code in the last 18 months because you've moved into "architecture" or "tech lead" roles — we will probably not move forward. This role writes code.

The skills inventory (please read carefully)
Most JDs list 20 skills and you're supposed to have all of them. We're going to do this differently.
Things you absolutely need
•	Production experience with embeddings-based retrieval systems (sentence-transformers, OpenAI embeddings, BGE, E5, or similar) deployed to real users. We don't care which model — we care that you've handled embedding drift, index refresh, retrieval-quality regression in production.
•	Production experience with vector databases or hybrid search infrastructure — Pinecone, Weaviate, Qdrant, Milvus, OpenSearch, Elasticsearch, FAISS, or something similar. Again, the specific tech doesn't matter; the operational experience does.
•	Strong Python. Yes really, we care about code quality.
•	Hands-on experience designing evaluation frameworks for ranking systems — NDCG, MRR, MAP, offline-to-online correlation, A/B test interpretation. If you've never thought about how to evaluate a ranking system rigorously, this role will be very painful.
Things we'd like you to have but won't reject you for
•	LLM fine-tuning experience (LoRA, QLoRA, PEFT)
•	Experience with learning-to-rank models (XGBoost-based or neural)
•	Prior exposure to HR-tech, recruiting tech, or marketplace products
•	Background in distributed systems or large-scale inference optimization
•	Open-source contributions in the AI/ML space
Things we explicitly do NOT want
This is the section most JDs skip but we think it's the most important:
•	Title-chasers. If your career trajectory shows you optimizing for "Senior" → "Staff" → "Principal" titles by switching companies every 1.5 years, we're not a fit. We need someone who plans to be here for 3+ years.
•	Framework enthusiasts. If your GitHub is full of LangChain tutorials and your blog posts are "How I used [hot framework] to build [demo]" — that's fine but it's not what we need. We need people who think about systems, not frameworks.
•	People who have only worked at consulting firms (TCS, Infosys, Wipro, Accenture, Cognizant, Capgemini, etc.) in their entire career. We've had bad fit experiences in both directions. If you're currently at one of these companies but have prior product-company experience, that's fine.
•	People whose primary expertise is computer vision, speech, or robotics without significant NLP/IR exposure. We respect your work but you'd be re-learning fundamentals here.
•	People whose work has been entirely on closed-source proprietary systems for 5+ years without external validation (papers, talks, open-source). We need to see how you think, not just trust that you can think.

On location, comp, and logistics
•	Location: Pune/Noida-preferred but flexible. We have offices in Noida and Pune(mostly used Tue/Thu). We don't require any specific number of in-office days but we expect quarterly travel for offsites. Candidates in Hyderabad, Pune, Mumbai, Delhi NCR welcome to apply. Outside India: case-by-case, but we don't sponsor work visas.
•	Notice period: We'd love sub-30-day notice. We can buy out up to 30 days. 30+ day notice candidates are still in scope but the bar gets higher.

The vibe check
We genuinely believe culture-fit matters more at this stage than skills-fit. Skills are teachable; the rest mostly isn't.
We work async-first and write a lot. If you find writing painful, you'll find this role painful.
We disagree openly and decide quickly. If you find that style abrasive, you'll find this role abrasive.
We move fast and break things, with the caveat that "things" are usually our internal assumptions, not user-facing systems. If you need a stable, mature codebase to be productive, you'll find this role unstable.

How to read between the lines
The "ideal candidate" we're imagining is roughly:
•	6-8 years total experience, of which 4-5 are in applied ML/AI roles at product companies (not pure services).
•	Has shipped at least one end-to-end ranking, search, or recommendation system to real users at meaningful scale.
•	Has strong opinions about retrieval (hybrid vs dense), evaluation (offline vs online), and LLM integration (when to fine-tune vs prompt) — and can defend them with reference to systems they actually built.
•	Located in or willing to relocate to Noida or Pune.
•	Active on Redrob platform (or has clear signal of being in the job market) so we can actually talk to them.
We are aware this is a narrow profile. We're not expecting to find many matches in a 100K candidate pool. We're explicitly OK with that — we'd rather see 10 great matches than 1000 maybes.

Final note for the participants of the Redrob hackathon
If you're reading this in the context of the Intelligent Candidate Discovery & Ranking Challenge:
The "right answer" to this JD is not "find candidates whose skills section contains the most AI keywords." That's a trap we've explicitly built into the dataset.
The right answer involves reasoning about the gap between what the JD says and what the JD means. A Tier 5 candidate may not use the words "RAG" or "Pinecone" in their profile, but if their career history shows they built a recommendation system at a product company, they're a fit. A candidate who has all the AI keywords listed as skills but whose title is "Marketing Manager" is not a fit, no matter how perfect their skill list looks.
Your ranking system should also weigh behavioral signals — a perfect-on-paper candidate who hasn't logged in for 6 months and has a 5% recruiter response rate is, for hiring purposes, not actually available. Down-weight them appropriately.
Good luck.

JD.docx"""

In [227]:
parsed_jd = jd_parser.parse(
    jd_text
)

print(parsed_jd.keys())

dict_keys(['role', 'min_exp', 'max_exp', 'jd_text'])

In [228]:
jd_embedding = embedding_engine.encode_jd(
    parsed_jd
)

print(jd_embedding.shape)

(384,)

In [371]:
#SUB DATASET

sample_df = df
print(sample_df.shape)

(100000, 8)

In [377]:
import time

start = time.time()

rows = sample_df.to_dict("records")

candidates = [

    {
        **candidate_parser.parse(row),
        **career_extractor.extract(
            row["career_history"]
        )
    }

    for row in rows
]

print("Candidates:", len(candidates))

print(
    "Seconds:",
    round(
        time.time() - start,
        2
    )
)

Candidates: 100000
Seconds: 6.22

In [378]:
import time

start = time.time()

embedding = embedding_engine.encode_candidate(
    candidates[0]
)

print(
    "Single Candidate:",
    round(
        time.time() - start,
        4
    ),
    "sec"
)

Single Candidate: 0.1944 sec

In [379]:
import time

start = time.time()

for candidate in candidates[:100]:

    embedding_engine.encode_candidate(
        candidate
    )

print(
    "100 Candidates:",
    round(
        time.time() - start,
        2
    ),
    "sec"
)

100 Candidates: 7.9 sec

In [ ]:

print(
    "100 Candidates:",
    round(
        time.time() - start,
        2
    ),
    "sec"
)

In [373]:
candidate_embeddings = []

for candidate in candidates:
    embedding = (
        embedding_engine.encode_candidate(
            candidate
        )
    )
    candidate_embeddings.append(
        embedding
    )
candidate_embeddings = np.array(
    candidate_embeddings
)

print(
    candidate_embeddings.shape
)

KeyboardInterrupt:

In [374]:
import faiss

dimension = (
    candidate_embeddings.shape[1]
)
index = faiss.IndexFlatIP(
    dimension
)
index.add(
    candidate_embeddings.astype(
        "float32"
    )
)
print(
    index.ntotal
)

AttributeError: 'list' object has no attribute 'shape'

In [233]:
scores, indices = index.search(
    jd_embedding.reshape(
        1,
        -1
    ).astype("float32"),
    50
)

print(indices.shape)
print(scores.shape)

(1, 50)
(1, 50)

In [234]:
for rank, idx in enumerate(
    indices[0][:10]
):

    candidate = candidates[idx]

    print(
        "=" * 80
    )

    print(
        f"Rank {rank+1}"
    )

    print(
        candidate["candidate_id"]
    )

    print(
        candidate["headline"]
    )

    print(
        candidate["current_title"]
    )

    print(
        candidate["years_experience"]
    )

================================================================================
Rank 1
CAND_0000969
AI Specialist | 5.5 yrs in analytics & ML
AI Specialist
5.5
================================================================================
Rank 2
CAND_0000422
AI Research Engineer | Data Science & ML enthusiast
AI Research Engineer
6.3
================================================================================
Rank 3
CAND_0000633
Software Engineer | 6.4+ yrs in data engineering
Software Engineer
6.4
================================================================================
Rank 4
CAND_0000874
Senior Software Engineer | SQL, Spark, Cloud
Senior Software Engineer
6.3
================================================================================
Rank 5
CAND_0000873
Senior Software Engineer | SQL, Spark, Cloud
Senior Software Engineer
2.1
================================================================================
Rank 6
CAND_0000859
Senior Software Engineer | SQL, Spark, Cloud
Senior Software Engineer
5.9
================================================================================
Rank 7
CAND_0000229
Senior Software Engineer | SQL, Spark, Cloud
Senior Software Engineer
2.2
================================================================================
Rank 8
CAND_0000184
Software Engineer | SQL, Spark, Cloud
Software Engineer
4.9
================================================================================
Rank 9
CAND_0000578
Data Engineer | 6.9+ yrs in data engineering
Data Engineer
6.9
================================================================================
Rank 10
CAND_0000852
Senior Software Engineer | 4.8+ yrs in data engineering
Senior Software Engineer
4.8

In [235]:
retrieved_candidates = []

for idx in indices[0]:

    candidate = candidates[idx]

    career_score = (
        career_match_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    retrieved_candidates.append({

        "candidate_id":
            candidate["candidate_id"],

        "headline":
            candidate["headline"],

        "career_score":
            career_score,

        "signal_score":
            signal_score,

        "candidate":
            candidate
    })

In [236]:
len(retrieved_candidates)

50

In [237]:
retrieved_candidates = sorted(

    retrieved_candidates,

    key=lambda x:
        x["career_score"],

    reverse=True
)

In [238]:
for row in retrieved_candidates[:10]:

    print("=" * 80)

    print(
        row["candidate_id"]
    )

    print(
        row["headline"]
    )

    print(
        "Career:",
        row["career_score"]
    )

    print(
        "Signal:",
        row["signal_score"]
    )

================================================================================
CAND_0000852
Senior Software Engineer | 4.8+ yrs in data engineering
Career: 33
Signal: 38.76
================================================================================
CAND_0000947
Analytics Engineer | 3.8+ yrs in data engineering
Career: 33
Signal: 49.03
================================================================================
CAND_0000874
Senior Software Engineer | SQL, Spark, Cloud
Career: 30
Signal: 40.26
================================================================================
CAND_0000665
Senior Software Engineer | 6.2+ yrs in data engineering
Career: 30
Signal: 68.44
================================================================================
CAND_0000452
Senior Data Engineer | 2.9+ yrs in data engineering
Career: 30
Signal: 26.46
================================================================================
CAND_0000584
Analytics Engineer | 7.3+ yrs in data engineering
Career: 30
Signal: 50.13
================================================================================
CAND_0000944
Senior Software Engineer | Data pipelines & analytics
Career: 30
Signal: 56.69
================================================================================
CAND_0000227
Data Analyst | 7.6+ yrs in data engineering
Career: 27
Signal: 22.33
================================================================================
CAND_0000082
Data Analyst | 7.4+ yrs in data engineering
Career: 27
Signal: 57.72
================================================================================
CAND_0000422
AI Research Engineer | Data Science & ML enthusiast
Career: 26
Signal: 68.33

In [239]:
for idx in indices[0][:20]:

    candidate = candidates[idx]

    print(
        candidate["current_title"]
    )

AI Specialist
AI Research Engineer
Software Engineer
Senior Software Engineer
Senior Software Engineer
Senior Software Engineer
Senior Software Engineer
Software Engineer
Data Engineer
Senior Software Engineer
Senior Software Engineer
Civil Engineer
HR Manager
HR Manager
HR Manager
Data Engineer
Senior Data Engineer
Software Engineer
Mechanical Engineer
Mechanical Engineer

In [240]:
from src.role_intelligence import (
    RoleIntelligenceEngine
)

role_engine = RoleIntelligenceEngine()

In [241]:
role_ranked = []

for idx in indices[0]:

    candidate = candidates[idx]

    role_score = role_engine.score(
        candidate
    )

    role_ranked.append({
        "candidate": candidate,
        "role_score": role_score
    })

role_ranked = sorted(
    role_ranked,
    key=lambda x: x["role_score"],
    reverse=True
)

In [242]:
for row in role_ranked[:20]:

    print("=" * 80)

    print(
        row["candidate"]["candidate_id"]
    )

    print(
        row["candidate"]["headline"]
    )

    print(
        "Role Score:",
        row["role_score"]
    )

================================================================================
CAND_0000874
Senior Software Engineer | SQL, Spark, Cloud
Role Score: 300
================================================================================
CAND_0000852
Senior Software Engineer | 4.8+ yrs in data engineering
Role Score: 300
================================================================================
CAND_0000422
AI Research Engineer | Data Science & ML enthusiast
Role Score: 200
================================================================================
CAND_0000633
Software Engineer | 6.4+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000859
Senior Software Engineer | SQL, Spark, Cloud
Role Score: 200
================================================================================
CAND_0000578
Data Engineer | 6.9+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000665
Senior Software Engineer | 6.2+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000682
Data Engineer | 2.6+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000705
AI Research Engineer | Building ML-powered solutions
Role Score: 200
================================================================================
CAND_0000390
Backend Engineer | 6.6+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000273
ML Engineer | 5.8 yrs in analytics & ML
Role Score: 200
================================================================================
CAND_0000944
Senior Software Engineer | Data pipelines & analytics
Role Score: 200
================================================================================
CAND_0000082
Data Analyst | 7.4+ yrs in data engineering
Role Score: 200
================================================================================
CAND_0000755
Software Engineer | Full-stack development
Role Score: 150
================================================================================
CAND_0000458
Software Engineer | Full-stack development
Role Score: 150
================================================================================
CAND_0000969
AI Specialist | 5.5 yrs in analytics & ML
Role Score: 100
================================================================================
CAND_0000873
Senior Software Engineer | SQL, Spark, Cloud
Role Score: 100
================================================================================
CAND_0000229
Senior Software Engineer | SQL, Spark, Cloud
Role Score: 100
================================================================================
CAND_0000184
Software Engineer | SQL, Spark, Cloud
Role Score: 100
================================================================================
CAND_0000996
Senior Data Engineer | SQL, Spark, Cloud
Role Score: 100

In [243]:
backend_count = 0

for candidate in candidates:

    title = candidate.get(
        "current_title",
        ""
    ).lower()

    if any(
        x in title
        for x in [
            "backend",
            "data engineer",
            "analytics engineer",
            "machine learning",
            "ml engineer",
            "software engineer"
        ]
    ):
        backend_count += 1

print(backend_count)

76

In [244]:
for candidate in candidates:

    title = candidate.get(
        "current_title",
        ""
    )

    if (
        "backend" in title.lower()
        or
        "data engineer" in title.lower()
        or
        "analytics engineer" in title.lower()
    ):

        print(
            candidate["candidate_id"],
            title
        )

CAND_0000001 Backend Engineer
CAND_0000010 Data Engineer
CAND_0000190 Backend Engineer
CAND_0000210 Senior Data Engineer
CAND_0000225 Analytics Engineer
CAND_0000343 Analytics Engineer
CAND_0000345 Data Engineer
CAND_0000354 Analytics Engineer
CAND_0000390 Backend Engineer
CAND_0000395 Analytics Engineer
CAND_0000411 Analytics Engineer
CAND_0000452 Senior Data Engineer
CAND_0000508 Backend Engineer
CAND_0000539 Backend Engineer
CAND_0000578 Data Engineer
CAND_0000584 Analytics Engineer
CAND_0000628 Analytics Engineer
CAND_0000649 Data Engineer
CAND_0000652 Backend Engineer
CAND_0000682 Data Engineer
CAND_0000797 Backend Engineer
CAND_0000820 Backend Engineer
CAND_0000878 Backend Engineer
CAND_0000947 Analytics Engineer
CAND_0000970 Data Engineer
CAND_0000996 Senior Data Engineer

In [245]:
for candidate in candidates:

    if candidate["candidate_id"] == "CAND_0000001":

        # print(candidate["candidate_text"])
        print(candidate["job_titles"])

['Backend Engineer', 'Analytics Engineer']

PARSER.PY

In [246]:
from importlib import reload
import src.parser

reload(src.parser)

from src.parser import CandidateParser

candidate_parser = CandidateParser()

print("Parser Reloaded")

Parser Reloaded

In [247]:
candidates = []

for _, row in sample_df.iterrows():

    parsed = candidate_parser.parse(row)

    career = career_extractor.extract(
        row["career_history"]
    )

    candidate = {
        **parsed,
        **career
    }

    candidates.append(candidate)

print(
    "Candidates:",
    len(candidates)
)

Candidates: 1000

In [248]:
candidate_embeddings = []

for candidate in candidates:

    embedding = (
        embedding_engine.encode_candidate(
            candidate
        )
    )

    candidate_embeddings.append(
        embedding
    )

candidate_embeddings = np.array(
    candidate_embeddings
)

print(
    candidate_embeddings.shape
)

(1000, 384)

In [249]:
import faiss

dimension = (
    candidate_embeddings.shape[1]
)

index = faiss.IndexFlatIP(
    dimension
)

index.add(
    candidate_embeddings.astype(
        "float32"
    )
)

print(
    "Index Size:",
    index.ntotal
)

Index Size: 1000

In [250]:
scores, indices = index.search(
    jd_embedding.reshape(
        1,
        -1
    ).astype("float32"),
    50
)

print(
    scores.shape
)

print(
    indices.shape
)

(1, 50)
(1, 50)

In [251]:
for rank, idx in enumerate(
    indices[0][:20]
):

    candidate = candidates[idx]

    print(
        f"{rank+1}.",
        candidate["current_title"]
    )

1. HR Manager
2. HR Manager
3. HR Manager
4. HR Manager
5. Civil Engineer
6. HR Manager
7. Mechanical Engineer
8. Operations Manager
9. Mechanical Engineer
10. Civil Engineer
11. Graphic Designer
12. Operations Manager
13. Operations Manager
14. Sales Executive
15. Operations Manager
16. Graphic Designer
17. HR Manager
18. Civil Engineer
19. Project Manager
20. Graphic Designer

EMBEDDING.PY

In [252]:
from importlib import reload
import src.embeddings

reload(src.embeddings)

from src.embeddings import EmbeddingEngine

embedding_engine = EmbeddingEngine()

print("Embedding Engine Reloaded")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Embedding Engine Reloaded

In [253]:
candidate_embeddings = []

for candidate in candidates:

    embedding = (
        embedding_engine.encode_candidate(
            candidate
        )
    )

    candidate_embeddings.append(
        embedding
    )

candidate_embeddings = np.array(
    candidate_embeddings
)

print(
    candidate_embeddings.shape
)

(1000, 384)

In [254]:
import faiss

dimension = candidate_embeddings.shape[1]

index = faiss.IndexFlatIP(
    dimension
)

index.add(
    candidate_embeddings.astype(
        "float32"
    )
)

print(index.ntotal)

1000

In [255]:
scores, indices = index.search(
    jd_embedding.reshape(
        1,
        -1
    ).astype("float32"),
    50
)

In [256]:
for rank, idx in enumerate(
    indices[0][:20]
):

    candidate = candidates[idx]

    print(
        f"{rank+1}.",
        candidate["current_title"]
    )

1. Java Developer
2. DevOps Engineer
3. QA Engineer
4. QA Engineer
5. DevOps Engineer
6. DevOps Engineer
7. QA Engineer
8. Frontend Engineer
9. Frontend Engineer
10. QA Engineer
11. Frontend Engineer
12. DevOps Engineer
13. Java Developer
14. QA Engineer
15. QA Engineer
16. Cloud Engineer
17. Java Developer
18. QA Engineer
19. Java Developer
20. Full Stack Developer

In [262]:
candidate = candidates[0]

print(candidate["candidate_id"])
print(candidate["current_title"])
print(candidate["candidate_text"])

CAND_0000001
Backend Engineer
Backend Engineer Backend Engineer | SQL, Spark, Cloud Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice. Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

In [263]:
candidate = candidates[0]

embedding = embedding_engine.encode_candidate(
    candidate
)

print(embedding.shape)

print(candidate["candidate_text"])

(384,)
Backend Engineer Backend Engineer | SQL, Spark, Cloud Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice. Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP

In [264]:
import inspect

print(
    inspect.getsource(
        embedding_engine.encode_candidate
    )
)

    def encode_candidate(
        self,
        candidate
    ):

        text = candidate.get(
            "candidate_text",
            ""
        )

        return self.encode_text(
            text
        )

In [265]:
print(candidates[0]["candidate_text"])
print(candidates[100]["candidate_text"])
print(candidates[500]["candidate_text"])

Backend Engineer Backend Engineer | SQL, Spark, Cloud Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice. Tailwind NLP Image Classification Fine-tuning LLMs Weights & Biases Speech Recognition Photoshop TTS LoRA Apache Beam AWS Flask BentoML Milvus GANs Statistical Modeling GCP
Customer Support Customer Support | Driving business outcomes Professional with 7.0+ years of experience. My professional background is in marketing manager — I've built and led teams, owned KPIs, and driven business outcomes in this domain. Lately I've been curious about how AI tools could augment my work — I've experimented with ChatGPT and a few other tools for productivity and content creation, and I think the space is exciting. Open to roles where I can apply my domain expertise alongside emerging AI capabilities. Project Management GraphQL TypeScript GCP Docker Kubernetes AWS CI/CD Snowflake
DevOps Engineer DevOps Engineer | Full-stack development Software engineer with 6.0 years of experience across web, backend, and cloud systems. Strong fundamentals in software development and system design. Most of my work is conventional backend engineering — APIs, databases, queues, deployments. I've been keeping up with AI/ML at a self-learner level — taken some online courses, played with the OpenAI and Anthropic APIs, built a small RAG side project — but I haven't done it in a professional capacity yet. Open to roles where I can either deepen my software engineering work or, if the team is open to it, start contributing to ML-adjacent systems. Django Sales Scrum Rust Statistical Modeling Redux BentoML Spring Boot

In [266]:
print(parsed_jd["role"])

Job Description: Senior AI Engineer — Founding TeamCompany: Redrob AI (Series A AI-native talent intelligence platform)

In [267]:
print(parsed_jd["jd_text"][:500])

Job Description: Senior AI Engineer — Founding TeamCompany: Redrob AI (Series A AI-native talent intelligence platform)
Location: Pune/Noida, India (Hybrid — flexible cadence) | Open to relocation candidates from Tier-1 Indian cities
Employment Type: Full-time
Experience Required: 5–9 years (see "what we mean by this" below)

Let's be honest about this role
We're going to write this JD differently from most. We're a Series A company that just raised our round and we're building a new AI Engineer

In [268]:
retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Search
Recommendation

Embeddings
Vector Database
Pinecone
Milvus
FAISS
Qdrant

Python
Spark
Airflow
Feature Engineering

Production ML
Learning To Rank
NDCG
MRR

5-9 years experience
"""

In [269]:
jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

print(jd_embedding.shape)

(384,)

In [270]:
# ==========================
# Build Retrieval Query
# ==========================

retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Search
Recommendation

Embeddings
Vector Database
Pinecone
Milvus
FAISS
Qdrant

Python
Spark
Airflow
Feature Engineering

Production ML
Learning To Rank
NDCG
MRR

5-9 years experience
"""

# ==========================
# Encode Query
# ==========================

jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

print(
    "JD Embedding Shape:",
    jd_embedding.shape
)

# ==========================
# Retrieve Top 50
# ==========================

scores, indices = index.search(
    jd_embedding.reshape(
        1,
        -1
    ).astype("float32"),
    1000
)

print(
    "Scores Shape:",
    scores.shape
)

print(
    "Indices Shape:",
    indices.shape
)

# ==========================
# Print Top 20 Results
# ==========================

for rank, idx in enumerate(
    indices[0][:20]
):

    candidate = candidates[idx]

    print(
        f"{rank+1}.",
        candidate["current_title"]
    )

JD Embedding Shape: (384,)
Scores Shape: (1, 1000)
Indices Shape: (1, 1000)
1. ML Engineer
2. AI Research Engineer
3. Senior Data Engineer
4. Senior Data Engineer
5. ML Engineer
6. AI Research Engineer
7. Backend Engineer
8. Senior Software Engineer
9. Data Engineer
10. Senior Software Engineer
11. Senior Software Engineer
12. Data Engineer
13. Recommendation Systems Engineer
14. Data Engineer
15. Analytics Engineer
16. Senior Software Engineer
17. ML Engineer
18. Data Engineer
19. Backend Engineer
20. Analytics Engineer

In [271]:
role_ranked = []

for idx in indices[0]:

    candidate = candidates[idx]

    role_score = role_engine.score(
        candidate
    )

    role_ranked.append({

        "candidate": candidate,

        "role_score": role_score
    })

role_ranked = sorted(
    role_ranked,
    key=lambda x: x["role_score"],
    reverse=True
)

for rank, row in enumerate(
    role_ranked[:20]
):

    candidate = row["candidate"]

    print(
        f"{rank+1}.",
        candidate["current_title"],
        "| Role Score:",
        row["role_score"]
    )

1. Senior Software Engineer | Role Score: 300
2. Analytics Engineer | Role Score: 300
3. Data Scientist | Role Score: 300
4. Senior Software Engineer | Role Score: 300
5. ML Engineer | Role Score: 200
6. AI Research Engineer | Role Score: 200
7. Senior Data Engineer | Role Score: 200
8. AI Research Engineer | Role Score: 200
9. Backend Engineer | Role Score: 200
10. Senior Software Engineer | Role Score: 200
11. Data Engineer | Role Score: 200
12. Recommendation Systems Engineer | Role Score: 200
13. Data Engineer | Role Score: 200
14. Senior Software Engineer | Role Score: 200
15. ML Engineer | Role Score: 200
16. Data Engineer | Role Score: 200
17. Backend Engineer | Role Score: 200
18. Software Engineer | Role Score: 200
19. Software Engineer | Role Score: 200
20. Senior Software Engineer | Role Score: 200

In [272]:
from src.final_ranker import (
    FinalRanker
)

ranker = FinalRanker()

In [273]:
from src.evidence_match import (
    EvidenceMatchEngine
)

evidence_engine = (
    EvidenceMatchEngine()
)

print("Evidence Engine Loaded")

Evidence Engine Loaded

In [274]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = role_engine.score(
        candidate
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = signal_engine.score(
        candidate
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = ranker.score(

        semantic_score=
            semantic_score,

        role_score=
            role_score,

        evidence_score=
            evidence_score,

        signal_score=
            signal_score,

        integrity_score=
            integrity_score
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(
        ranked_candidates
    )
)

1000

In [275]:
print(
    ranked_candidates[0].keys()
)

dict_keys(['candidate', 'semantic_score', 'role_score', 'evidence_score', 'signal_score', 'integrity_score', 'final_score'])

In [276]:
top100 = ranked_candidates[:100]

print(len(top100))

100

In [277]:
for row in ranked_candidates[:20]:

    c = row["candidate"]

    print("=" * 80)

    print(
        c["candidate_id"]
    )

    print(
        c["current_title"]
    )

    print(
        "Semantic:",
        round(
            row["semantic_score"],
            3
        )
    )

    print(
        "Role:",
        row["role_score"]
    )

    print(
        "Evidence:",
        row["evidence_score"]
    )

    print(
        "Signal:",
        round(
            row["signal_score"],
            2
        )
    )

    print(
        "Final:",
        row["final_score"]
    )

================================================================================
CAND_0000666
Data Scientist
Semantic: 0.787
Role: 300
Evidence: 27
Signal: 56.83
Final: 417.28
================================================================================
CAND_0000874
Senior Software Engineer
Semantic: 0.786
Role: 300
Evidence: 26
Signal: 40.26
Final: 405.99
================================================================================
CAND_0000343
Analytics Engineer
Semantic: 0.813
Role: 300
Evidence: 22
Signal: 52.83
Final: 400.54
================================================================================
CAND_0000852
Senior Software Engineer
Semantic: 0.823
Role: 300
Evidence: 24
Signal: 38.76
Final: 399.61
================================================================================
CAND_0000031
Recommendation Systems Engineer
Semantic: 0.819
Role: 200
Evidence: 29
Signal: 69.36
Final: 329.87
================================================================================
CAND_0000665
Senior Software Engineer
Semantic: 0.825
Role: 200
Evidence: 28
Signal: 68.44
Final: 326.47
================================================================================
CAND_0000944
Senior Software Engineer
Semantic: 0.815
Role: 200
Evidence: 28
Signal: 56.69
Final: 320.49
================================================================================
CAND_0000001
Backend Engineer
Semantic: 0.784
Role: 200
Evidence: 28
Signal: 52.23
Final: 317.96
================================================================================
CAND_0000775
Software Engineer
Semantic: 0.776
Role: 200
Evidence: 27
Signal: 51.96
Final: 314.74
================================================================================
CAND_0000422
AI Research Engineer
Semantic: 0.831
Role: 200
Evidence: 24
Signal: 68.33
Final: 314.47
================================================================================
CAND_0000973
Software Engineer
Semantic: 0.784
Role: 200
Evidence: 27
Signal: 25.68
Final: 301.68
================================================================================
CAND_0000454
Data Analyst
Semantic: 0.746
Role: 200
Evidence: 27
Signal: 26.19
Final: 301.56
================================================================================
CAND_0000970
Data Engineer
Semantic: 0.814
Role: 200
Evidence: 21
Signal: 58.99
Final: 300.64
================================================================================
CAND_0000633
Software Engineer
Semantic: 0.807
Role: 200
Evidence: 21
Signal: 59.13
Final: 300.63
================================================================================
CAND_0000878
Backend Engineer
Semantic: 0.826
Role: 200
Evidence: 22
Signal: 52.67
Final: 300.59
================================================================================
CAND_0000354
Analytics Engineer
Semantic: 0.786
Role: 200
Evidence: 18
Signal: 53.72
Final: 288.72
================================================================================
CAND_0000578
Data Engineer
Semantic: 0.825
Role: 200
Evidence: 21
Signal: 30.92
Final: 286.71
================================================================================
CAND_0000082
Data Analyst
Semantic: 0.793
Role: 200
Evidence: 16
Signal: 57.72
Final: 284.79
================================================================================
CAND_0000273
ML Engineer
Semantic: 0.814
Role: 200
Evidence: 13
Signal: 72.73
Final: 283.51
================================================================================
CAND_0000981
ML Engineer
Semantic: 0.848
Role: 200
Evidence: 19
Signal: 33.75
Final: 282.35

In [278]:
for row in ranked_candidates[:20]:

    print(
        row["candidate"]["current_title"]
    )

Data Scientist
Senior Software Engineer
Analytics Engineer
Senior Software Engineer
Recommendation Systems Engineer
Senior Software Engineer
Senior Software Engineer
Backend Engineer
Software Engineer
AI Research Engineer
Software Engineer
Data Analyst
Data Engineer
Software Engineer
Backend Engineer
Analytics Engineer
Data Engineer
Data Analyst
ML Engineer
ML Engineer

In [279]:
from src.integrity_engine import (
    IntegrityEngine
)

integrity_engine = (
    IntegrityEngine()
)

print("Integrity Engine Loaded")

Integrity Engine Loaded

In [280]:
for cid in [

    "CAND_0000001",
    "CAND_0000225",
    "CAND_0000330"

]:

    row = df[
        df["candidate_id"] == cid
    ].iloc[0]

    parsed = candidate_parser.parse(
        row
    )

    career = career_extractor.extract(
        row["career_history"]
    )

    candidate = {
        **parsed,
        **career
    }

    print(
        candidate["current_title"]
    )

    print(
        integrity_engine.score(
            candidate
        )
    )

    print("-" * 40)

Backend Engineer
100
----------------------------------------
Analytics Engineer
100
----------------------------------------
Civil Engineer
100
----------------------------------------

In [281]:
integrity_score = (
    integrity_engine.score(
        candidate
    )
)

In [282]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = role_engine.score(
        candidate
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = ranker.score(

        semantic_score=
            semantic_score,

        role_score=
            role_score,

        evidence_score=
            evidence_score,

        signal_score=
            signal_score,

        integrity_score=
            integrity_score
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(
        ranked_candidates
    )
)

1000

In [283]:
import inspect

print(
    inspect.getsource(
        ranker.score
    )
)

OSError: could not get source code

In [284]:
from src.final_ranker import FinalRanker

ranker = FinalRanker()

print(type(ranker))

import inspect

print(
    inspect.signature(
        ranker.score
    )
)

<class 'src.final_ranker.FinalRanker'>
(semantic_score, role_score, evidence_score, signal_score, integrity_score)

In [285]:
from importlib import reload

import src.final_ranker

reload(src.final_ranker)

from src.final_ranker import FinalRanker

ranker = FinalRanker()

import inspect

print(
    inspect.signature(
        ranker.score
    )
)

ModuleNotFoundError: spec not found for the module 'src.final_ranker'

In [286]:
for row in ranked_candidates[:10]:

    c = row["candidate"]

    print("=" * 80)

    print(c["candidate_id"])

    print(c["current_title"])

    print("Semantic:", round(row["semantic_score"], 3))

    print("Role:", row["role_score"])

    print("Evidence:", row["evidence_score"])

    print("Signal:", round(row["signal_score"], 2))

    print("Integrity:", row["integrity_score"])

    print("Final:", row["final_score"])

================================================================================
CAND_0000666
Data Scientist
Semantic: 0.787
Role: 300
Evidence: 27
Signal: 56.83
Integrity: 100
Final: 417.28
================================================================================
CAND_0000874
Senior Software Engineer
Semantic: 0.786
Role: 300
Evidence: 26
Signal: 40.26
Integrity: 100
Final: 405.99
================================================================================
CAND_0000343
Analytics Engineer
Semantic: 0.813
Role: 300
Evidence: 22
Signal: 52.83
Integrity: 100
Final: 400.54
================================================================================
CAND_0000852
Senior Software Engineer
Semantic: 0.823
Role: 300
Evidence: 24
Signal: 38.76
Integrity: 100
Final: 399.61
================================================================================
CAND_0000031
Recommendation Systems Engineer
Semantic: 0.819
Role: 200
Evidence: 29
Signal: 69.36
Integrity: 100
Final: 329.87
================================================================================
CAND_0000665
Senior Software Engineer
Semantic: 0.825
Role: 200
Evidence: 28
Signal: 68.44
Integrity: 100
Final: 326.47
================================================================================
CAND_0000944
Senior Software Engineer
Semantic: 0.815
Role: 200
Evidence: 28
Signal: 56.69
Integrity: 100
Final: 320.49
================================================================================
CAND_0000001
Backend Engineer
Semantic: 0.784
Role: 200
Evidence: 28
Signal: 52.23
Integrity: 100
Final: 317.96
================================================================================
CAND_0000775
Software Engineer
Semantic: 0.776
Role: 200
Evidence: 27
Signal: 51.96
Integrity: 100
Final: 314.74
================================================================================
CAND_0000422
AI Research Engineer
Semantic: 0.831
Role: 200
Evidence: 24
Signal: 68.33
Integrity: 100
Final: 314.47

In [287]:
print(len(ranked_candidates))

1000

In [288]:
print(indices.shape)

(1, 1000)

In [289]:
print(indices)

[[980 704 209 451 199 421 877 664 577 228 851 648  30 681 946 943 272 969
  507 342   9 538 995 389 632 627 796 439 154 583 224 858 872 183 394 116
  396 610 674 651 164 301  43 189  81 344 109 559 819 297 410 848 151 665
  873 929 353 781 111 426   0 972 227  14 714 723 977 868 157 645 812 883
  135 197 968 869 262 927  90 563 535 129 212 273 226 774 479  71 843 237
  181 159 765 942 528 425 574 516 732  66 976 950 521 919 552  55 936 307
  233 646 106 634 959 614 813 184 248 804 284 983 130 125  13 748 914 254
  690 195 630 677 347 918 798 984 312 371 789  95 616  22 374  60 769 833
  979 678 351 865 334  53  50 287 717 784 539 705 759 498 736 493 711 276
  718 838  24 441 236  10 468 857 739 599 502  76 294 955 506 467 395 910
  997 456  58 626 973 108 466 306 854 916  17  45 587 908 598 803 867 476
   89 363  19 444 904 719 836 522 785 419  59 532 787  42 494 417 715 405
   85   6 932 754 949 687 380 393 329 542 381 357 897   8 581 825 600 201
  790 296 533 150 453 606 332 289 764 488 216 136 855 569 835 653  70 776
  544 820 875 486 235 741 747 595 102 232 880 104 912 515 703 382 853 898
   84 168 330 291 261  92 870 225 906 221 146 964 500 940 675 218 198 457
  922 477 633 432 155  96 902 965  51 990  61 894 871 302  21  48 293  88
   34  25 888 406 156 303 970 121 629 480 934 901 242 771  54 954 327 117
  179 716 416 322 890 120 385 316 801  37 926 205 250 800 694 576 738 770
  186 989 925 471 295 613 876 138 744 701 982 937 314 850 654 766  74 740
  133 170  26 591 824 481 134 222 826 390 636 746 255 680 132 356 706 957
  928 491 142 259 935 951 692 103 409 378  52 249 580 489 400 246 594  87
  562 757 448 797 847 139 460 143 509 446 597 603 346 348 579 283 863 952
  697 526 525 319 546 737 127 974 947  31 311  12 619 726 756 442 211 992
  188 571 355 763 427 609 190 292 349 617 244 827  82 702 814 698 369 119
  241 420 256 207 407 424 962 673 823 110 931 725 364 649 861 158 428  20
  529 611 503 564 358 310 161  98 214 100 549  56 582 191 622  44 107 123
  540 903 465 817 253 670 366 710  68 809 115 484 485  79  73 635 234 359
  203 933 618   2 279 360 309 640 683 882 920 695 511 523 177 615 999  72
  567  47 354 517 768 907 779 398 141 325 623 266 215 829 128 589 290 219
  783 667 735 251 966  36 755 991 335 666 713 874 686 960 846 988 905 558
  849 811 402 682  93 513 561 941 537 403 497 434 454 637 696 592 961 137
    7  91   1 720 663 985 449 530 844 885 891 392 270 220 321 174 126   5
  802  18 866 461 194 631 496 624 144 772 305  16  67 210 326 408 152 978
  994 304 608 388 841 753 727 760 387 643 987 840 700 196 238 113  78 547
  504 423  35 708 343 458 780 585 775 900 165 745 176 986 672 412 352  62
  418 208 642  86 172  23 148 575 267 655 166 274 806 566 265 185  69 998
  339 361 839 438 258  99 761 641 993 786  64 815 644 323 505 944 924 551
  413 415 229 510 939 895 689 730 884 508 401 202 831 886 658 281 331 837
  404 175 482 638  32 777 112 893 300 422 131 721 487 584 192 818  83 204
  118 308 794 317 383 586 193 981 662 553 282 524 527 953  39 313 795 474
  782  28 178 299 472  65 899 462 550 656 167 463 223 464 751 492 743 180
   97 288 278 554 200 923 889 333 245 437 605 340 160 285 971 376 443 742
  478 243 762 621 459 834 271 264 370 429 661 499 124 469 328 602 578  41
  337 399 810 731 628 647 676 440 483 431 414 475 263  11 639 230 182 101
   49 367 518 519 163 921 799 315 277 545 722 734 807 345 712 967  33 963
  206 239 187 368 830 650 514 269 386 945 162  63 805 728 173 612  77  38
  791   3 996  94 878 671 625 217  27 231 114 450 375 816 685 433 268 557
  668 913 240 958 455 531 773 145 752  46 750 534 384 435 411 842 555 860
  707 793 147 490 320 541 821 758 512 213 324 660 892 657 788 852  40 909
  915 447 365 548 822 669 620 318 543 252 140 975 588 247 286  80 377 362
  659 896 257 590 930 879 436 938 604 679 280   4 379 724 260 749 607 556
  699 350 570 652 495 572 560 693 568 778 473 338 596 169 688 862 153 391
  859 948 341 445 372 336 275 536 149 767 956 430  15  57 565 887 881 501
   29 397 729 832 911 373 593 709 520 470 864 808 733 917  75 691 792 828
  856 171 573 452 601 105 845 122 298 684]]

In [290]:
print(len(indices[0]))

1000

In [291]:
print(scores.shape)
print(scores)

(1, 1000)
[[0.84787065 0.84548426 0.8348509  0.83277506 0.8327719  0.83087325
  0.82593197 0.8253182  0.82516515 0.82369    0.823249   0.8193157
  0.8185123  0.81738615 0.81735957 0.8149656  0.8143983  0.81426
  0.8137604  0.81254375 0.81139076 0.8103124  0.8099625  0.8072543
  0.80687135 0.8047622  0.80442095 0.8043765  0.80420804 0.80390954
  0.80335253 0.80106777 0.79810524 0.7980186  0.79759187 0.79696345
  0.7967154  0.79496795 0.7946722  0.79437625 0.7939194  0.79332703
  0.79311436 0.79273933 0.79261297 0.7924606  0.79138774 0.79104173
  0.78894407 0.78845865 0.78731835 0.7872813  0.7868683  0.78658915
  0.78638655 0.7861725  0.78566176 0.7853082  0.78491133 0.7841104
  0.7840482  0.7836063  0.7826186  0.78258395 0.7820286  0.781887
  0.78152215 0.7813747  0.7810812  0.78078574 0.78077453 0.7801716
  0.78003776 0.7798102  0.7797426  0.7796773  0.77860653 0.7782011
  0.7776761  0.77767396 0.7776667  0.7769868  0.77694625 0.77641934
  0.77637064 0.7761141  0.77600193 0.77521944 0.7751363  0.77498716
  0.77497965 0.7746234  0.7744875  0.7744839  0.77424705 0.7739819
  0.773813   0.77375257 0.7733346  0.77309036 0.7730896  0.7730197
  0.7729542  0.7724488  0.7723811  0.771502   0.77100855 0.7706987
  0.7706784  0.77067137 0.77020943 0.7702043  0.7701059  0.7699753
  0.76983094 0.7696135  0.7694996  0.7692658  0.7692045  0.76913375
  0.76887965 0.7688794  0.7686765  0.76857054 0.7682991  0.7680138
  0.7680122  0.76787364 0.76719546 0.76714975 0.7669001  0.76684225
  0.7666386  0.76663256 0.7660394  0.7657493  0.7656689  0.765595
  0.76521623 0.765175   0.76511943 0.76505196 0.764991   0.76497316
  0.7649174  0.7649121  0.7647517  0.76408637 0.76352566 0.76350474
  0.76324326 0.76302737 0.76283205 0.7624886  0.76248467 0.76246876
  0.7624648  0.7624377  0.7624254  0.7622941  0.7622349  0.7621614
  0.7617524  0.76173496 0.761732   0.76144624 0.7614074  0.76120687
  0.7608429  0.76037395 0.7599135  0.7598118  0.75965846 0.7592988
  0.7591916  0.75879806 0.7587203  0.75866896 0.75853914 0.7583399
  0.7583248  0.75812495 0.7581075  0.7577629  0.7574121  0.75732625
  0.7572961  0.75704014 0.7570022  0.7567956  0.7566647  0.7565385
  0.7563457  0.7561847  0.75562495 0.75561917 0.75541943 0.7544062
  0.75423217 0.75398445 0.7539726  0.75392693 0.75375277 0.75370955
  0.7536386  0.7535069  0.7533927  0.7533911  0.7523207  0.7522579
  0.75186455 0.7517729  0.7516119  0.75138235 0.7511974  0.7503573
  0.7503249  0.7500994  0.7497149  0.7496585  0.7489655  0.74891263
  0.74884313 0.7486713  0.7486119  0.74857384 0.74836266 0.74819225
  0.747908   0.747871   0.7478124  0.7477525  0.74768734 0.74733555
  0.7472799  0.7471585  0.7470119  0.74675965 0.74621034 0.745803
  0.7458027  0.74569553 0.7456682  0.7456161  0.7454997  0.74518144
  0.744804   0.74475384 0.7446077  0.74426854 0.74424964 0.7440773
  0.7440097  0.7439027  0.7438663  0.7437612  0.7434777  0.74308383
  0.742934   0.74275506 0.7421701  0.74211776 0.7420846  0.741988
  0.7417331  0.74155176 0.74130845 0.741205   0.74118316 0.74102646
  0.7408843  0.7404311  0.7401433  0.7400602  0.7399608  0.7397013
  0.73931676 0.7390218  0.7387211  0.7385224  0.73829055 0.73778164
  0.73747134 0.73718643 0.73657334 0.7360037  0.7354783  0.73521376
  0.73491    0.7346877  0.7346755  0.7345854  0.73431647 0.7342855
  0.73416555 0.7341118  0.7338522  0.73372334 0.7331983  0.7331967
  0.7326113  0.73241925 0.7323046  0.7321292  0.7319487  0.73134357
  0.7311698  0.73093694 0.7308526  0.73045605 0.7302958  0.72937715
  0.7288472  0.7282436  0.728134   0.72776425 0.72762454 0.7270045
  0.72668064 0.72653747 0.72587097 0.72552633 0.7252999  0.7252821
  0.72506696 0.72501177 0.72492135 0.72465914 0.72444296 0.7243823
  0.7241841  0.7240803  0.72404766 0.7238505  0.72353417 0.7233664
  0.7231211  0.72300386 0.7226068  0.7225357  0.7225324  0.7224474
  0.72241795 0.72222835 0.7220863  0.7219626  0.7218046  0.721209
  0.7211561  0.7210753  0.72085214 0.7206656  0.72055227 0.7199553
  0.7198522  0.719578   0.71935326 0.71896607 0.7187896  0.7186534
  0.71860397 0.71851707 0.7183196  0.71772885 0.7176665  0.71759117
  0.7175343  0.7175046  0.7174538  0.71727383 0.717239   0.7171518
  0.71706206 0.7165681  0.7159761  0.7157301  0.71561253 0.71537185
  0.7151835  0.7142229  0.71402574 0.7140058  0.71376324 0.7136222
  0.7135787  0.71356374 0.7135319  0.7135146  0.71335256 0.71324056
  0.7127543  0.711956   0.71176547 0.711594   0.7113346  0.7111042
  0.7110163  0.7105055  0.71043813 0.71033525 0.71025026 0.7102331
  0.709913   0.7096857  0.70934737 0.7089945  0.708902   0.7087386
  0.7087266  0.70864475 0.70858413 0.70853686 0.70848835 0.70831436
  0.70765597 0.7076528  0.70760685 0.7072077  0.7071579  0.7071402
  0.7069328  0.7067996  0.70666015 0.7065331  0.70569307 0.7056532
  0.7056222  0.7053118  0.7050973  0.70393604 0.7038375  0.7037067
  0.7034705  0.70332205 0.70307434 0.70297045 0.702854   0.70266455
  0.7025456  0.70253664 0.70246565 0.7024095  0.702218   0.70220554
  0.7020227  0.70200044 0.7012441  0.7009918  0.70095587 0.70095253
  0.7008383  0.7006709  0.70064235 0.70040107 0.70021695 0.6999893
  0.69993323 0.69979346 0.69963354 0.6992767  0.69909203 0.69904375
  0.6986762  0.6984639  0.69830024 0.6982548  0.69805866 0.69790584
  0.6978539  0.69752985 0.69744784 0.6973288  0.69700754 0.6968349
  0.69658154 0.69586796 0.6954106  0.6953684  0.69518214 0.69517255
  0.6950902  0.6950804  0.6947588  0.694701   0.694589   0.6940837
  0.6940682  0.6936314  0.69293785 0.69293284 0.69284606 0.6926582
  0.6926581  0.692631   0.69241965 0.6923664  0.69220626 0.69219375
  0.69215953 0.6921464  0.692083   0.6918514  0.69181633 0.6917745
  0.69149995 0.6914266  0.6913236  0.6912245  0.69118893 0.69081414
  0.69075555 0.6905829  0.690265   0.6901789  0.6899826  0.68987834
  0.6897926  0.6896657  0.6896286  0.68950367 0.6894882  0.6892511
  0.68915355 0.6891372  0.68894726 0.6888838  0.6888443  0.6887582
  0.68850386 0.68831503 0.6882204  0.68793887 0.6878466  0.6877455
  0.6877077  0.6872535  0.6872337  0.6871029  0.68708265 0.6870097
  0.6869761  0.68694556 0.6868739  0.6868716  0.68684375 0.6867959
  0.6867937  0.6867821  0.6867403  0.68674016 0.6866688  0.686425
  0.6862541  0.6861694  0.6861464  0.68585974 0.6858586  0.68584096
  0.6857071  0.6851858  0.6850873  0.6846929  0.68457454 0.6843823
  0.68430996 0.6842023  0.6840173  0.6839752  0.68396074 0.683686
  0.68358845 0.6835401  0.6833801  0.68295383 0.6828832  0.6827529
  0.68252003 0.6824787  0.68226075 0.68220747 0.6820978  0.68205637
  0.68205523 0.6819546  0.6817395  0.6817071  0.68141425 0.6814008
  0.68138266 0.68128514 0.6812711  0.6811484  0.6811236  0.6810628
  0.68098116 0.6809286  0.68092835 0.6808531  0.6806783  0.6806544
  0.6805083  0.6803908  0.680339   0.6803336  0.68022215 0.6800548
  0.67996716 0.6794905  0.67940474 0.6793802  0.6793021  0.67930055
  0.6790252  0.6789644  0.67866474 0.67858565 0.6785093  0.67842686
  0.67828524 0.678215   0.6781339  0.6779567  0.67782694 0.67775744
  0.6777204  0.6776693  0.67766535 0.6776528  0.6773941  0.67738235
  0.6771481  0.67690927 0.676826   0.67680687 0.6767937  0.6767596
  0.6765214  0.6763789  0.67625976 0.6757111  0.6756424  0.6754782
  0.67542464 0.6753283  0.67530334 0.6751337  0.6749414  0.67487025
  0.67479587 0.6747412  0.6745801  0.6743967  0.67433745 0.6743125
  0.6741722  0.67408895 0.67405254 0.674016   0.67398584 0.673918
  0.67370886 0.67361045 0.6735389  0.6733719  0.6732975  0.6732967
  0.6732547  0.6731956  0.6731918  0.67317444 0.67316353 0.67303735
  0.6729171  0.6728738  0.6727414  0.67273474 0.6727164  0.6726033
  0.672287   0.67217135 0.672151   0.67179257 0.6717042  0.6715485
  0.67151344 0.67147267 0.6713326  0.6712476  0.6710718  0.6710261
  0.6710199  0.67073655 0.6706615  0.6705982  0.6705722  0.67051494
  0.6704011  0.67035425 0.670124   0.6700545  0.6699139  0.6697802
  0.66977924 0.6697188  0.669524   0.669364   0.669351   0.6691456
  0.66889906 0.6683903  0.6683463  0.6681529  0.66812396 0.6680222
  0.66776943 0.667612   0.66754997 0.66745925 0.66745055 0.6674122
  0.667099   0.66703045 0.6669781  0.66696095 0.66689265 0.66667306
  0.66653013 0.6664014  0.66639656 0.6663035  0.66627604 0.6661514
  0.6660119  0.66572374 0.66569865 0.6655834  0.6655217  0.66545403
  0.6654209  0.66527945 0.6652007  0.66511965 0.6650878  0.6650212
  0.66494244 0.66475433 0.6647189  0.6642018  0.66396964 0.66392505
  0.66380715 0.6636608  0.66333115 0.6632402  0.6629934  0.66290903
  0.66259    0.6622713  0.66225874 0.6622039  0.6619954  0.6615859
  0.6614695  0.66137344 0.661372   0.6613518  0.66120017 0.66106683
  0.66098243 0.6608887  0.66051567 0.66043514 0.6603799  0.6600592
  0.66004837 0.659899   0.6596054  0.65950096 0.6593863  0.65937316
  0.65896255 0.65874434 0.65873814 0.658689   0.6586327  0.6586288
  0.6585839  0.6584384  0.6584201  0.6581968  0.65793276 0.6579018
  0.6578077  0.65763456 0.6571459  0.65709114 0.6568236  0.65663993
  0.65662766 0.6566217  0.6565957  0.65658283 0.6564834  0.6564293
  0.656287   0.6562506  0.6562449  0.6559118  0.65587    0.6558091
  0.65578103 0.65537935 0.6553183  0.6550985  0.65497243 0.65489906
  0.65473634 0.6546895  0.65427065 0.6541121  0.6540108  0.65399194
  0.6539664  0.65380806 0.6532099  0.65317    0.6531083  0.6529244
  0.6528388  0.65281796 0.652708   0.652628   0.65219104 0.65218633
  0.65214306 0.65211093 0.65200627 0.6519128  0.65176433 0.6514553
  0.6514009  0.65139794 0.65118647 0.65118015 0.6509682  0.650939
  0.65089077 0.65076447 0.6505217  0.6503506  0.65016377 0.6500028
  0.64985216 0.64956224 0.64943314 0.6494187  0.6493668  0.64928436
  0.6492747  0.6490997  0.6481974  0.6480589  0.6477593  0.64772284
  0.64759827 0.6475662  0.64740264 0.64718425 0.64717484 0.6471402
  0.6471232  0.64705044 0.6470468  0.6469808  0.64682275 0.64675313
  0.6465152  0.64622235 0.64604807 0.64593446 0.64583385 0.6457982
  0.64570504 0.6456421  0.6455295  0.6454458  0.6452383  0.645166
  0.64512444 0.64511293 0.6450329  0.6447569  0.6443162  0.64430684
  0.6437692  0.64327395 0.64319336 0.64312506 0.642768   0.6426381
  0.64249897 0.64223707 0.6422168  0.64216864 0.64186394 0.64173627
  0.64163643 0.6414042  0.6412679  0.64097637 0.64088064 0.6406399
  0.64034617 0.6400953  0.63979554 0.63977486 0.63872075 0.6385582
  0.6384896  0.6381465  0.6379789  0.637675   0.63753206 0.63724077
  0.63700676 0.6369214  0.6367952  0.6366268  0.6364534  0.63617134
  0.6360525  0.6360018  0.63591063 0.63588744 0.635736   0.63543546
  0.63528734 0.63511026 0.6350247  0.63492393 0.63433623 0.6341754
  0.6341203  0.63401973 0.63395894 0.6337999  0.63367313 0.6333749
  0.6332685  0.63287693 0.6328497  0.6323423  0.6317725  0.63144803
  0.6313908  0.6312813  0.63098955 0.630978   0.6308227  0.6305983
  0.63057315 0.6304984  0.6302973  0.6301951  0.6300668  0.630036
  0.6294973  0.6291332  0.6290915  0.62859046 0.62812424 0.6281029
  0.6280421  0.6278643  0.6277334  0.62772954 0.6274508  0.62714493
  0.6267413  0.62600505 0.6250458  0.6218623  0.6217129  0.6215503
  0.62068564 0.6205416  0.6201533  0.6200517  0.61973804 0.6191566
  0.619116   0.6176671  0.61697716 0.6162442  0.6162181  0.6156422
  0.6146163  0.6135764  0.6085291  0.6067536 ]]

In [292]:
ranked_candidates = []

print("Before Loop:", len(ranked_candidates))

for rank_pos, idx in enumerate(indices[0]):

    print("Processing:", rank_pos)

    candidate = candidates[idx]

    semantic_score = float(scores[0][rank_pos])

    role_score = role_engine.score(candidate)

    evidence_score = evidence_engine.score(candidate)

    signal_score = signal_engine.score(candidate)

    integrity_score = integrity_engine.score(candidate)

    final_score = ranker.score(
        semantic_score,
        role_score,
        evidence_score,
        signal_score,
        integrity_score
    )

    ranked_candidates.append({
        "candidate": candidate,
        "final_score": final_score
    })

print("After Loop:", len(ranked_candidates))

Before Loop: 0
Processing: 0
Processing: 1
Processing: 2
Processing: 3
Processing: 4
Processing: 5
Processing: 6
Processing: 7
Processing: 8
Processing: 9
Processing: 10
Processing: 11
Processing: 12
Processing: 13
Processing: 14
Processing: 15
Processing: 16
Processing: 17
Processing: 18
Processing: 19
Processing: 20
Processing: 21
Processing: 22
Processing: 23
Processing: 24
Processing: 25
Processing: 26
Processing: 27
Processing: 28
Processing: 29
Processing: 30
Processing: 31
Processing: 32
Processing: 33
Processing: 34
Processing: 35
Processing: 36
Processing: 37
Processing: 38
Processing: 39
Processing: 40
Processing: 41
Processing: 42
Processing: 43
Processing: 44
Processing: 45
Processing: 46
Processing: 47
Processing: 48
Processing: 49
Processing: 50
Processing: 51
Processing: 52
Processing: 53
Processing: 54
Processing: 55
Processing: 56
Processing: 57
Processing: 58
Processing: 59
Processing: 60
Processing: 61
Processing: 62
Processing: 63
Processing: 64
Processing: 65
Processing: 66
Processing: 67
Processing: 68
Processing: 69
Processing: 70
Processing: 71
Processing: 72
Processing: 73
Processing: 74
Processing: 75
Processing: 76
Processing: 77
Processing: 78
Processing: 79
Processing: 80
Processing: 81
Processing: 82
Processing: 83
Processing: 84
Processing: 85
Processing: 86
Processing: 87
Processing: 88
Processing: 89
Processing: 90
Processing: 91
Processing: 92
Processing: 93
Processing: 94
Processing: 95
Processing: 96
Processing: 97
Processing: 98
Processing: 99
Processing: 100
Processing: 101
Processing: 102
Processing: 103
Processing: 104
Processing: 105
Processing: 106
Processing: 107
Processing: 108
Processing: 109
Processing: 110
Processing: 111
Processing: 112
Processing: 113
Processing: 114
Processing: 115
Processing: 116
Processing: 117
Processing: 118
Processing: 119
Processing: 120
Processing: 121
Processing: 122
Processing: 123
Processing: 124
Processing: 125
Processing: 126
Processing: 127
Processing: 128
Processing: 129
Processing: 130
Processing: 131
Processing: 132
Processing: 133
Processing: 134
Processing: 135
Processing: 136
Processing: 137
Processing: 138
Processing: 139
Processing: 140
Processing: 141
Processing: 142
Processing: 143
Processing: 144
Processing: 145
Processing: 146
Processing: 147
Processing: 148
Processing: 149
Processing: 150
Processing: 151
Processing: 152
Processing: 153
Processing: 154
Processing: 155
Processing: 156
Processing: 157
Processing: 158
Processing: 159
Processing: 160
Processing: 161
Processing: 162
Processing: 163
Processing: 164
Processing: 165
Processing: 166
Processing: 167
Processing: 168
Processing: 169
Processing: 170
Processing: 171
Processing: 172
Processing: 173
Processing: 174
Processing: 175
Processing: 176
Processing: 177
Processing: 178
Processing: 179
Processing: 180
Processing: 181
Processing: 182
Processing: 183
Processing: 184
Processing: 185
Processing: 186
Processing: 187
Processing: 188
Processing: 189
Processing: 190
Processing: 191
Processing: 192
Processing: 193
Processing: 194
Processing: 195
Processing: 196
Processing: 197
Processing: 198
Processing: 199
Processing: 200
Processing: 201
Processing: 202
Processing: 203
Processing: 204
Processing: 205
Processing: 206
Processing: 207
Processing: 208
Processing: 209
Processing: 210
Processing: 211
Processing: 212
Processing: 213
Processing: 214
Processing: 215
Processing: 216
Processing: 217
Processing: 218
Processing: 219
Processing: 220
Processing: 221
Processing: 222
Processing: 223
Processing: 224
Processing: 225
Processing: 226
Processing: 227
Processing: 228
Processing: 229
Processing: 230
Processing: 231
Processing: 232
Processing: 233
Processing: 234
Processing: 235
Processing: 236
Processing: 237
Processing: 238
Processing: 239
Processing: 240
Processing: 241
Processing: 242
Processing: 243
Processing: 244
Processing: 245
Processing: 246
Processing: 247
Processing: 248
Processing: 249
Processing: 250
Processing: 251
Processing: 252
Processing: 253
Processing: 254
Processing: 255
Processing: 256
Processing: 257
Processing: 258
Processing: 259
Processing: 260
Processing: 261
Processing: 262
Processing: 263
Processing: 264
Processing: 265
Processing: 266
Processing: 267
Processing: 268
Processing: 269
Processing: 270
Processing: 271
Processing: 272
Processing: 273
Processing: 274
Processing: 275
Processing: 276
Processing: 277
Processing: 278
Processing: 279
Processing: 280
Processing: 281
Processing: 282
Processing: 283
Processing: 284
Processing: 285
Processing: 286
Processing: 287
Processing: 288
Processing: 289
Processing: 290
Processing: 291
Processing: 292
Processing: 293
Processing: 294
Processing: 295
Processing: 296
Processing: 297
Processing: 298
Processing: 299
Processing: 300
Processing: 301
Processing: 302
Processing: 303
Processing: 304
Processing: 305
Processing: 306
Processing: 307
Processing: 308
Processing: 309
Processing: 310
Processing: 311
Processing: 312
Processing: 313
Processing: 314
Processing: 315
Processing: 316
Processing: 317
Processing: 318
Processing: 319
Processing: 320
Processing: 321
Processing: 322
Processing: 323
Processing: 324
Processing: 325
Processing: 326
Processing: 327
Processing: 328
Processing: 329
Processing: 330
Processing: 331
Processing: 332
Processing: 333
Processing: 334
Processing: 335
Processing: 336
Processing: 337
Processing: 338
Processing: 339
Processing: 340
Processing: 341
Processing: 342
Processing: 343
Processing: 344
Processing: 345
Processing: 346
Processing: 347
Processing: 348
Processing: 349
Processing: 350
Processing: 351
Processing: 352
Processing: 353
Processing: 354
Processing: 355
Processing: 356
Processing: 357
Processing: 358
Processing: 359
Processing: 360
Processing: 361
Processing: 362
Processing: 363
Processing: 364
Processing: 365
Processing: 366
Processing: 367
Processing: 368
Processing: 369
Processing: 370
Processing: 371
Processing: 372
Processing: 373
Processing: 374
Processing: 375
Processing: 376
Processing: 377
Processing: 378
Processing: 379
Processing: 380
Processing: 381
Processing: 382
Processing: 383
Processing: 384
Processing: 385
Processing: 386
Processing: 387
Processing: 388
Processing: 389
Processing: 390
Processing: 391
Processing: 392
Processing: 393
Processing: 394
Processing: 395
Processing: 396
Processing: 397
Processing: 398
Processing: 399
Processing: 400
Processing: 401
Processing: 402
Processing: 403
Processing: 404
Processing: 405
Processing: 406
Processing: 407
Processing: 408
Processing: 409
Processing: 410
Processing: 411
Processing: 412
Processing: 413
Processing: 414
Processing: 415
Processing: 416
Processing: 417
Processing: 418
Processing: 419
Processing: 420
Processing: 421
Processing: 422
Processing: 423
Processing: 424
Processing: 425
Processing: 426
Processing: 427
Processing: 428
Processing: 429
Processing: 430
Processing: 431
Processing: 432
Processing: 433
Processing: 434
Processing: 435
Processing: 436
Processing: 437
Processing: 438
Processing: 439
Processing: 440
Processing: 441
Processing: 442
Processing: 443
Processing: 444
Processing: 445
Processing: 446
Processing: 447
Processing: 448
Processing: 449
Processing: 450
Processing: 451
Processing: 452
Processing: 453
Processing: 454
Processing: 455
Processing: 456
Processing: 457
Processing: 458
Processing: 459
Processing: 460
Processing: 461
Processing: 462
Processing: 463
Processing: 464
Processing: 465
Processing: 466
Processing: 467
Processing: 468
Processing: 469
Processing: 470
Processing: 471
Processing: 472
Processing: 473
Processing: 474
Processing: 475
Processing: 476
Processing: 477
Processing: 478
Processing: 479
Processing: 480
Processing: 481
Processing: 482
Processing: 483
Processing: 484
Processing: 485
Processing: 486
Processing: 487
Processing: 488
Processing: 489
Processing: 490
Processing: 491
Processing: 492
Processing: 493
Processing: 494
Processing: 495
Processing: 496
Processing: 497
Processing: 498
Processing: 499
Processing: 500
Processing: 501
Processing: 502
Processing: 503
Processing: 504
Processing: 505
Processing: 506
Processing: 507
Processing: 508
Processing: 509
Processing: 510
Processing: 511
Processing: 512
Processing: 513
Processing: 514
Processing: 515
Processing: 516
Processing: 517
Processing: 518
Processing: 519
Processing: 520
Processing: 521
Processing: 522
Processing: 523
Processing: 524
Processing: 525
Processing: 526
Processing: 527
Processing: 528
Processing: 529
Processing: 530
Processing: 531
Processing: 532
Processing: 533
Processing: 534
Processing: 535
Processing: 536
Processing: 537
Processing: 538
Processing: 539
Processing: 540
Processing: 541
Processing: 542
Processing: 543
Processing: 544
Processing: 545
Processing: 546
Processing: 547
Processing: 548
Processing: 549
Processing: 550
Processing: 551
Processing: 552
Processing: 553
Processing: 554
Processing: 555
Processing: 556
Processing: 557
Processing: 558
Processing: 559
Processing: 560
Processing: 561
Processing: 562
Processing: 563
Processing: 564
Processing: 565
Processing: 566
Processing: 567
Processing: 568
Processing: 569
Processing: 570
Processing: 571
Processing: 572
Processing: 573
Processing: 574
Processing: 575
Processing: 576
Processing: 577
Processing: 578
Processing: 579
Processing: 580
Processing: 581
Processing: 582
Processing: 583
Processing: 584
Processing: 585
Processing: 586
Processing: 587
Processing: 588
Processing: 589
Processing: 590
Processing: 591
Processing: 592
Processing: 593
Processing: 594
Processing: 595
Processing: 596
Processing: 597
Processing: 598
Processing: 599
Processing: 600
Processing: 601
Processing: 602
Processing: 603
Processing: 604
Processing: 605
Processing: 606
Processing: 607
Processing: 608
Processing: 609
Processing: 610
Processing: 611
Processing: 612
Processing: 613
Processing: 614
Processing: 615
Processing: 616
Processing: 617
Processing: 618
Processing: 619
Processing: 620
Processing: 621
Processing: 622
Processing: 623
Processing: 624
Processing: 625
Processing: 626
Processing: 627
Processing: 628
Processing: 629
Processing: 630
Processing: 631
Processing: 632
Processing: 633
Processing: 634
Processing: 635
Processing: 636
Processing: 637
Processing: 638
Processing: 639
Processing: 640
Processing: 641
Processing: 642
Processing: 643
Processing: 644
Processing: 645
Processing: 646
Processing: 647
Processing: 648
Processing: 649
Processing: 650
Processing: 651
Processing: 652
Processing: 653
Processing: 654
Processing: 655
Processing: 656
Processing: 657
Processing: 658
Processing: 659
Processing: 660
Processing: 661
Processing: 662
Processing: 663
Processing: 664
Processing: 665
Processing: 666
Processing: 667
Processing: 668
Processing: 669
Processing: 670
Processing: 671
Processing: 672
Processing: 673
Processing: 674
Processing: 675
Processing: 676
Processing: 677
Processing: 678
Processing: 679
Processing: 680
Processing: 681
Processing: 682
Processing: 683
Processing: 684
Processing: 685
Processing: 686
Processing: 687
Processing: 688
Processing: 689
Processing: 690
Processing: 691
Processing: 692
Processing: 693
Processing: 694
Processing: 695
Processing: 696
Processing: 697
Processing: 698
Processing: 699
Processing: 700
Processing: 701
Processing: 702
Processing: 703
Processing: 704
Processing: 705
Processing: 706
Processing: 707
Processing: 708
Processing: 709
Processing: 710
Processing: 711
Processing: 712
Processing: 713
Processing: 714
Processing: 715
Processing: 716
Processing: 717
Processing: 718
Processing: 719
Processing: 720
Processing: 721
Processing: 722
Processing: 723
Processing: 724
Processing: 725
Processing: 726
Processing: 727
Processing: 728
Processing: 729
Processing: 730
Processing: 731
Processing: 732
Processing: 733
Processing: 734
Processing: 735
Processing: 736
Processing: 737
Processing: 738
Processing: 739
Processing: 740
Processing: 741
Processing: 742
Processing: 743
Processing: 744
Processing: 745
Processing: 746
Processing: 747
Processing: 748
Processing: 749
Processing: 750
Processing: 751
Processing: 752
Processing: 753
Processing: 754
Processing: 755
Processing: 756
Processing: 757
Processing: 758
Processing: 759
Processing: 760
Processing: 761
Processing: 762
Processing: 763
Processing: 764
Processing: 765
Processing: 766
Processing: 767
Processing: 768
Processing: 769
Processing: 770
Processing: 771
Processing: 772
Processing: 773
Processing: 774
Processing: 775
Processing: 776
Processing: 777
Processing: 778
Processing: 779
Processing: 780
Processing: 781
Processing: 782
Processing: 783
Processing: 784
Processing: 785
Processing: 786
Processing: 787
Processing: 788
Processing: 789
Processing: 790
Processing: 791
Processing: 792
Processing: 793
Processing: 794
Processing: 795
Processing: 796
Processing: 797
Processing: 798
Processing: 799
Processing: 800
Processing: 801
Processing: 802
Processing: 803
Processing: 804
Processing: 805
Processing: 806
Processing: 807
Processing: 808
Processing: 809
Processing: 810
Processing: 811
Processing: 812
Processing: 813
Processing: 814
Processing: 815
Processing: 816
Processing: 817
Processing: 818
Processing: 819
Processing: 820
Processing: 821
Processing: 822
Processing: 823
Processing: 824
Processing: 825
Processing: 826
Processing: 827
Processing: 828
Processing: 829
Processing: 830
Processing: 831
Processing: 832
Processing: 833
Processing: 834
Processing: 835
Processing: 836
Processing: 837
Processing: 838
Processing: 839
Processing: 840
Processing: 841
Processing: 842
Processing: 843
Processing: 844
Processing: 845
Processing: 846
Processing: 847
Processing: 848
Processing: 849
Processing: 850
Processing: 851
Processing: 852
Processing: 853
Processing: 854
Processing: 855
Processing: 856
Processing: 857
Processing: 858
Processing: 859
Processing: 860
Processing: 861
Processing: 862
Processing: 863
Processing: 864
Processing: 865
Processing: 866
Processing: 867
Processing: 868
Processing: 869
Processing: 870
Processing: 871
Processing: 872
Processing: 873
Processing: 874
Processing: 875
Processing: 876
Processing: 877
Processing: 878
Processing: 879
Processing: 880
Processing: 881
Processing: 882
Processing: 883
Processing: 884
Processing: 885
Processing: 886
Processing: 887
Processing: 888
Processing: 889
Processing: 890
Processing: 891
Processing: 892
Processing: 893
Processing: 894
Processing: 895
Processing: 896
Processing: 897
Processing: 898
Processing: 899
Processing: 900
Processing: 901
Processing: 902
Processing: 903
Processing: 904
Processing: 905
Processing: 906
Processing: 907
Processing: 908
Processing: 909
Processing: 910
Processing: 911
Processing: 912
Processing: 913
Processing: 914
Processing: 915
Processing: 916
Processing: 917
Processing: 918
Processing: 919
Processing: 920
Processing: 921
Processing: 922
Processing: 923
Processing: 924
Processing: 925
Processing: 926
Processing: 927
Processing: 928
Processing: 929
Processing: 930
Processing: 931
Processing: 932
Processing: 933
Processing: 934
Processing: 935
Processing: 936
Processing: 937
Processing: 938
Processing: 939
Processing: 940
Processing: 941
Processing: 942
Processing: 943
Processing: 944
Processing: 945
Processing: 946
Processing: 947
Processing: 948
Processing: 949
Processing: 950
Processing: 951
Processing: 952
Processing: 953
Processing: 954
Processing: 955
Processing: 956
Processing: 957
Processing: 958
Processing: 959
Processing: 960
Processing: 961
Processing: 962
Processing: 963
Processing: 964
Processing: 965
Processing: 966
Processing: 967
Processing: 968
Processing: 969
Processing: 970
Processing: 971
Processing: 972
Processing: 973
Processing: 974
Processing: 975
Processing: 976
Processing: 977
Processing: 978
Processing: 979
Processing: 980
Processing: 981
Processing: 982
Processing: 983
Processing: 984
Processing: 985
Processing: 986
Processing: 987
Processing: 988
Processing: 989
Processing: 990
Processing: 991
Processing: 992
Processing: 993
Processing: 994
Processing: 995
Processing: 996
Processing: 997
Processing: 998
Processing: 999
After Loop: 1000

In [293]:
print(ranked_candidates[:3])

[{'candidate': {'candidate_id': 'CAND_0000981', 'headline': 'ML Engineer | Data Science & ML enthusiast', 'summary': "Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like collaborative filtering and gradient-boosted models. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level.", 'location': 'Bhubaneswar, Odisha', 'country': 'India', 'years_experience': 6.4, 'current_title': 'ML Engineer', 'current_company': 'Wysa', 'company_size': '51-200', 'industry': 'HealthTech AI', 'skill_names': ['Semantic Search', 'Computer Vision', 'Image Classification', 'SQL', 'Data Science', 'scikit-learn', 'GANs', 'pgvector', 'Pinecone', 'Next.js', 'Airflow', 'OpenSearch', 'MLflow', 'OpenCV'], 'skill_text': 'Semantic Search Computer Vision Image Classification SQL Data Science scikit-learn GANs pgvector Pinecone Next.js Airflow OpenSearch MLflow OpenCV', 'num_skills': 14, 'certification_names': [], 'num_certifications': 0, 'education_tier': 'tier_2', 'has_relevant_degree': 0, 'highest_degree': 'B.E.', 'profile_score': 89.9, 'open_to_work': 0, 'response_rate': 0.55, 'avg_response_time': 116.5, 'profile_views': 89, 'applications': 3, 'github_score': 70.3, 'search_appearance': 373, 'saved_by_recruiters': 1, 'interview_completion': 0.92, 'offer_acceptance': -1, 'connection_count': 1181, 'endorsements': 125, 'notice_period_days': 120, 'preferred_work_mode': 'onsite', 'willing_to_relocate': 0, 'verified_email': 0, 'verified_phone': 1, 'linkedin_connected': 1, 'skill_assessment_avg': -1, 'skill_assessment_count': 0, 'days_since_active': 123, 'candidate_text': "ML Engineer ML Engineer | Data Science & ML enthusiast Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like collaborative filtering and gradient-boosted models. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level. Semantic Search Computer Vision Image Classification SQL Data Science scikit-learn GANs pgvector Pinecone Next.js Airflow OpenSearch MLflow OpenCV", 'current_role': 'ML Engineer', 'total_duration_months': 76, 'num_companies': 2, 'industries': ['HealthTech AI', 'SaaS'], 'job_titles': ['ML Engineer', 'Senior Software Engineer (ML)'], 'experience_text': 'ML Engineer HealthTech AI Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranking over engagement signals. Pure ML side of the work; production deployment was handled by the platform team. Senior Software Engineer (ML) SaaS Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.', 'career_growth_score': 1}, 'final_score': 282.35}, {'candidate': {'candidate_id': 'CAND_0000705', 'headline': 'AI Research Engineer | Building ML-powered solutions', 'summary': "Data scientist / ML engineer with 3.6 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level.", 'location': 'Indore, Madhya Pradesh', 'country': 'India', 'years_experience': 3.6, 'current_title': 'AI Research Engineer', 'current_company': 'Zomato', 'company_size': '5001-10000', 'industry': 'Food Delivery', 'skill_names': ['LoRA', 'Elasticsearch', 'OpenCV', 'GANs', 'TTS', 'RAG', 'Data Science', 'NLP', 'BentoML', 'PEFT', 'Statistical Modeling', 'Computer Vision', 'Haystack', 'Diffusion Models', 'Redis'], 'skill_text': 'LoRA Elasticsearch OpenCV GANs TTS RAG Data Science NLP BentoML PEFT Statistical Modeling Computer Vision Haystack Diffusion Models Redis', 'num_skills': 15, 'certification_names': [], 'num_certifications': 0, 'education_tier': 'tier_2', 'has_relevant_degree': 1, 'highest_degree': 'M.Tech', 'profile_score': 82.2, 'open_to_work': 0, 'response_rate': 0.34, 'avg_response_time': 115.0, 'profile_views': 128, 'applications': 5, 'github_score': 75.1, 'search_appearance': 572, 'saved_by_recruiters': 4, 'interview_completion': 0.58, 'offer_acceptance': -1, 'connection_count': 595, 'endorsements': 73, 'notice_period_days': 60, 'preferred_work_mode': 'flexible', 'willing_to_relocate': 1, 'verified_email': 1, 'verified_phone': 1, 'linkedin_connected': 1, 'skill_assessment_avg': 66.3, 'skill_assessment_count': 3, 'days_since_active': 59, 'candidate_text': "AI Research Engineer AI Research Engineer | Building ML-powered solutions Data scientist / ML engineer with 3.6 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level. LoRA Elasticsearch OpenCV GANs TTS RAG Data Science NLP BentoML PEFT Statistical Modeling Computer Vision Haystack Diffusion Models Redis", 'current_role': 'AI Research Engineer', 'total_duration_months': 43, 'num_companies': 2, 'industries': ['E-commerce', 'Food Delivery'], 'job_titles': ['AI Research Engineer', 'Junior ML Engineer'], 'experience_text': "AI Research Engineer Food Delivery Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service. Most of my project work has been in CV; I'm now interested in transitioning toward NLP/LLM work but my professional experience there is limited. Junior ML Engineer E-commerce Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning experiments for dynamic pricing but those didn't make it to production. The work was a mix of modeling, analysis, and stakeholder communication with the operations team.", 'career_growth_score': 0}, 'final_score': 273.37}, {'candidate': {'candidate_id': 'CAND_0000210', 'headline': 'Senior Data Engineer | Data pipelines & analytics', 'summary': "Software / data professional with 6.3 years of experience building data pipelines, backend systems, and analytics infrastructure. Started my career in backend engineering and gradually moved closer to data — first dashboards, then ETL, now some basic ML. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.", 'location': 'Berlin', 'country': 'Germany', 'years_experience': 6.3, 'current_title': 'Senior Data Engineer', 'current_company': 'upGrad', 'company_size': '1001-5000', 'industry': 'EdTech', 'skill_names': ['Computer Vision', 'Accounting', 'GANs', 'Object Detection', 'Angular', 'Speech Recognition', 'Learning to Rank', 'Statistical Modeling', 'LlamaIndex', 'JavaScript', 'LangChain'], 'skill_text': 'Computer Vision Accounting GANs Object Detection Angular Speech Recognition Learning to Rank Statistical Modeling LlamaIndex JavaScript LangChain', 'num_skills': 11, 'certification_names': [], 'num_certifications': 0, 'education_tier': 'tier_4', 'has_relevant_degree': 0, 'highest_degree': 'B.Tech', 'profile_score': 66.5, 'open_to_work': 0, 'response_rate': 0.6000000000000001, 'avg_response_time': 24.3, 'profile_views': 93, 'applications': 0, 'github_score': 61.8, 'search_appearance': 30, 'saved_by_recruiters': 14, 'interview_completion': 0.53, 'offer_acceptance': 0.79, 'connection_count': 942, 'endorsements': 59, 'notice_period_days': 120, 'preferred_work_mode': 'hybrid', 'willing_to_relocate': 0, 'verified_email': 1, 'verified_phone': 1, 'linkedin_connected': 0, 'skill_assessment_avg': -1, 'skill_assessment_count': 0, 'days_since_active': 90, 'candidate_text': "Senior Data Engineer Senior Data Engineer | Data pipelines & analytics Software / data professional with 6.3 years of experience building data pipelines, backend systems, and analytics infrastructure. Started my career in backend engineering and gradually moved closer to data — first dashboards, then ETL, now some basic ML. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice. Computer Vision Accounting GANs Object Detection Angular Speech Recognition Learning to Rank Statistical Modeling LlamaIndex JavaScript LangChain", 'current_role': 'Senior Data Engineer', 'total_duration_months': 74, 'num_companies': 3, 'industries': ['EdTech', 'Fintech', 'Manufacturing'], 'job_titles': ['Senior Data Engineer', 'Backend Engineer', 'Data Engineer'], 'experience_text': "Senior Data Engineer EdTech Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as performance optimization (query tuning, cluster sizing, materialized views). Also built the lineage and documentation framework now in use across the data org. Backend Engineer Manufacturing Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (Looker). Shipped a couple of small predictive features but the bulk of the role was data infrastructure. Data Engineer Fintech Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as performance optimization (query tuning, cluster sizing, materialized views). Also built the lineage and documentation framework now in use across the data org.", 'career_growth_score': 1}, 'final_score': 260.95}]

In [294]:
# ==========================
# Build Retrieval Query
# ==========================

retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Search
Recommendation

Embeddings
Vector Database
Pinecone
Milvus
FAISS
Qdrant

Python
Spark
Airflow
Feature Engineering

Production ML
Learning To Rank
NDCG
MRR

5-9 years experience
"""

# ==========================
# Encode Query
# ==========================

jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

print(
    "JD Embedding Shape:",
    jd_embedding.shape
)

# ==========================
# Retrieve Top 1000
# ==========================

scores, indices = index.search(
    jd_embedding.reshape(
        1,
        -1
    ).astype("float32"),
    1000
)

print(
    "Scores Shape:",
    scores.shape
)

print(
    "Indices Shape:",
    indices.shape
)

# ==========================
# Print Top 20 Results
# ==========================

for rank, idx in enumerate(
    indices[0][:20]
):

    candidate = candidates[idx]

    print(
        f"{rank+1}.",
        candidate["current_title"]
    )

# ==========================
# Verification
# ==========================

print("\nTotal Retrieved:")

print(
    len(
        indices[0]
    )
)

JD Embedding Shape: (384,)
Scores Shape: (1, 1000)
Indices Shape: (1, 1000)
1. ML Engineer
2. AI Research Engineer
3. Senior Data Engineer
4. Senior Data Engineer
5. ML Engineer
6. AI Research Engineer
7. Backend Engineer
8. Senior Software Engineer
9. Data Engineer
10. Senior Software Engineer
11. Senior Software Engineer
12. Data Engineer
13. Recommendation Systems Engineer
14. Data Engineer
15. Analytics Engineer
16. Senior Software Engineer
17. ML Engineer
18. Data Engineer
19. Backend Engineer
20. Analytics Engineer

Total Retrieved:
1000

In [295]:
print(
    len(
        ranked_candidates
    )
)

1000

In [296]:
top100 = ranked_candidates[:100]

print(
    len(
        top100
    )
)

100

In [297]:
print(len(indices[0]))

1000

In [298]:
indices[0]

array([980, 704, 209, 451, 199, 421, 877, 664, 577, 228, 851, 648,  30,
       681, 946, 943, 272, 969, 507, 342,   9, 538, 995, 389, 632, 627,
       796, 439, 154, 583, 224, 858, 872, 183, 394, 116, 396, 610, 674,
       651, 164, 301,  43, 189,  81, 344, 109, 559, 819, 297, 410, 848,
       151, 665, 873, 929, 353, 781, 111, 426,   0, 972, 227,  14, 714,
       723, 977, 868, 157, 645, 812, 883, 135, 197, 968, 869, 262, 927,
        90, 563, 535, 129, 212, 273, 226, 774, 479,  71, 843, 237, 181,
       159, 765, 942, 528, 425, 574, 516, 732,  66, 976, 950, 521, 919,
       552,  55, 936, 307, 233, 646, 106, 634, 959, 614, 813, 184, 248,
       804, 284, 983, 130, 125,  13, 748, 914, 254, 690, 195, 630, 677,
       347, 918, 798, 984, 312, 371, 789,  95, 616,  22, 374,  60, 769,
       833, 979, 678, 351, 865, 334,  53,  50, 287, 717, 784, 539, 705,
       759, 498, 736, 493, 711, 276, 718, 838,  24, 441, 236,  10, 468,
       857, 739, 599, 502,  76, 294, 955, 506, 467, 395, 910, 997, 456,
        58, 626, 973, 108, 466, 306, 854, 916,  17,  45, 587, 908, 598,
       803, 867, 476,  89, 363,  19, 444, 904, 719, 836, 522, 785, 419,
        59, 532, 787,  42, 494, 417, 715, 405,  85,   6, 932, 754, 949,
       687, 380, 393, 329, 542, 381, 357, 897,   8, 581, 825, 600, 201,
       790, 296, 533, 150, 453, 606, 332, 289, 764, 488, 216, 136, 855,
       569, 835, 653,  70, 776, 544, 820, 875, 486, 235, 741, 747, 595,
       102, 232, 880, 104, 912, 515, 703, 382, 853, 898,  84, 168, 330,
       291, 261,  92, 870, 225, 906, 221, 146, 964, 500, 940, 675, 218,
       198, 457, 922, 477, 633, 432, 155,  96, 902, 965,  51, 990,  61,
       894, 871, 302,  21,  48, 293,  88,  34,  25, 888, 406, 156, 303,
       970, 121, 629, 480, 934, 901, 242, 771,  54, 954, 327, 117, 179,
       716, 416, 322, 890, 120, 385, 316, 801,  37, 926, 205, 250, 800,
       694, 576, 738, 770, 186, 989, 925, 471, 295, 613, 876, 138, 744,
       701, 982, 937, 314, 850, 654, 766,  74, 740, 133, 170,  26, 591,
       824, 481, 134, 222, 826, 390, 636, 746, 255, 680, 132, 356, 706,
       957, 928, 491, 142, 259, 935, 951, 692, 103, 409, 378,  52, 249,
       580, 489, 400, 246, 594,  87, 562, 757, 448, 797, 847, 139, 460,
       143, 509, 446, 597, 603, 346, 348, 579, 283, 863, 952, 697, 526,
       525, 319, 546, 737, 127, 974, 947,  31, 311,  12, 619, 726, 756,
       442, 211, 992, 188, 571, 355, 763, 427, 609, 190, 292, 349, 617,
       244, 827,  82, 702, 814, 698, 369, 119, 241, 420, 256, 207, 407,
       424, 962, 673, 823, 110, 931, 725, 364, 649, 861, 158, 428,  20,
       529, 611, 503, 564, 358, 310, 161,  98, 214, 100, 549,  56, 582,
       191, 622,  44, 107, 123, 540, 903, 465, 817, 253, 670, 366, 710,
        68, 809, 115, 484, 485,  79,  73, 635, 234, 359, 203, 933, 618,
         2, 279, 360, 309, 640, 683, 882, 920, 695, 511, 523, 177, 615,
       999,  72, 567,  47, 354, 517, 768, 907, 779, 398, 141, 325, 623,
       266, 215, 829, 128, 589, 290, 219, 783, 667, 735, 251, 966,  36,
       755, 991, 335, 666, 713, 874, 686, 960, 846, 988, 905, 558, 849,
       811, 402, 682,  93, 513, 561, 941, 537, 403, 497, 434, 454, 637,
       696, 592, 961, 137,   7,  91,   1, 720, 663, 985, 449, 530, 844,
       885, 891, 392, 270, 220, 321, 174, 126,   5, 802,  18, 866, 461,
       194, 631, 496, 624, 144, 772, 305,  16,  67, 210, 326, 408, 152,
       978, 994, 304, 608, 388, 841, 753, 727, 760, 387, 643, 987, 840,
       700, 196, 238, 113,  78, 547, 504, 423,  35, 708, 343, 458, 780,
       585, 775, 900, 165, 745, 176, 986, 672, 412, 352,  62, 418, 208,
       642,  86, 172,  23, 148, 575, 267, 655, 166, 274, 806, 566, 265,
       185,  69, 998, 339, 361, 839, 438, 258,  99, 761, 641, 993, 786,
        64, 815, 644, 323, 505, 944, 924, 551, 413, 415, 229, 510, 939,
       895, 689, 730, 884, 508, 401, 202, 831, 886, 658, 281, 331, 837,
       404, 175, 482, 638,  32, 777, 112, 893, 300, 422, 131, 721, 487,
       584, 192, 818,  83, 204, 118, 308, 794, 317, 383, 586, 193, 981,
       662, 553, 282, 524, 527, 953,  39, 313, 795, 474, 782,  28, 178,
       299, 472,  65, 899, 462, 550, 656, 167, 463, 223, 464, 751, 492,
       743, 180,  97, 288, 278, 554, 200, 923, 889, 333, 245, 437, 605,
       340, 160, 285, 971, 376, 443, 742, 478, 243, 762, 621, 459, 834,
       271, 264, 370, 429, 661, 499, 124, 469, 328, 602, 578,  41, 337,
       399, 810, 731, 628, 647, 676, 440, 483, 431, 414, 475, 263,  11,
       639, 230, 182, 101,  49, 367, 518, 519, 163, 921, 799, 315, 277,
       545, 722, 734, 807, 345, 712, 967,  33, 963, 206, 239, 187, 368,
       830, 650, 514, 269, 386, 945, 162,  63, 805, 728, 173, 612,  77,
        38, 791,   3, 996,  94, 878, 671, 625, 217,  27, 231, 114, 450,
       375, 816, 685, 433, 268, 557, 668, 913, 240, 958, 455, 531, 773,
       145, 752,  46, 750, 534, 384, 435, 411, 842, 555, 860, 707, 793,
       147, 490, 320, 541, 821, 758, 512, 213, 324, 660, 892, 657, 788,
       852,  40, 909, 915, 447, 365, 548, 822, 669, 620, 318, 543, 252,
       140, 975, 588, 247, 286,  80, 377, 362, 659, 896, 257, 590, 930,
       879, 436, 938, 604, 679, 280,   4, 379, 724, 260, 749, 607, 556,
       699, 350, 570, 652, 495, 572, 560, 693, 568, 778, 473, 338, 596,
       169, 688, 862, 153, 391, 859, 948, 341, 445, 372, 336, 275, 536,
       149, 767, 956, 430,  15,  57, 565, 887, 881, 501,  29, 397, 729,
       832, 911, 373, 593, 709, 520, 470, 864, 808, 733, 917,  75, 691,
       792, 828, 856, 171, 573, 452, 601, 105, 845, 122, 298, 684])

In [299]:
len(indices[0])

1000

In [300]:
print(len(ranked_candidates))

1000

In [301]:
top100 = ranked_candidates[:100]

print(len(top100))

100

In [302]:
top100 = ranked_candidates[:100]

for row in top100[:25]:

    print(
        row["candidate"]["current_title"]
    )

ML Engineer
AI Research Engineer
Senior Data Engineer
Senior Data Engineer
ML Engineer
AI Research Engineer
Backend Engineer
Senior Software Engineer
Data Engineer
Senior Software Engineer
Senior Software Engineer
Data Engineer
Recommendation Systems Engineer
Data Engineer
Analytics Engineer
Senior Software Engineer
ML Engineer
Data Engineer
Backend Engineer
Analytics Engineer
Data Engineer
Backend Engineer
Senior Data Engineer
Backend Engineer
Software Engineer

In [303]:
bad_roles = 0

for row in top100:

    title = row[
        "candidate"
    ][
        "current_title"
    ].lower()

    if any(
        x in title
        for x in [

            "civil",
            "mechanical",
            "hr",
            "marketing",
            "sales",
            "customer support"

        ]
    ):

        bad_roles += 1

print(
    "Bad Roles:",
    bad_roles
)

Bad Roles: 0

In [304]:
submission_rows = []

for rank, row in enumerate(
    top100,
    start=1
):

    candidate = row["candidate"]

    submission_rows.append({

        "rank":
            rank,

        "candidate_id":
            candidate["candidate_id"],

        "score":
            row["final_score"]
    })

submission_df = pd.DataFrame(
    submission_rows
)

submission_df.head()

   rank  candidate_id   score
0     1  CAND_0000981  282.35
1     2  CAND_0000705  273.37
2     3  CAND_0000210  260.95
3     4  CAND_0000452  202.56
4     5  CAND_0000200  163.81

reason generator

In [305]:
ranked_candidates.append({

    "candidate":
        candidate,

    "semantic_score":
        semantic_score,

    "role_score":
        role_score,

    "evidence_score":
        evidence_score,

    "signal_score":
        signal_score,

    "integrity_score":
        integrity_score,

    "final_score":
        final_score
})

In [306]:
top100 = ranked_candidates[:100]

print(len(top100))

100

In [307]:
len(df)

100000

In [308]:
from importlib import reload

import src.reason_generator

reload(
    src.reason_generator
)

from src.reason_generator import (
    ReasonGenerator
)

reason_generator = (
    ReasonGenerator()
)

print(
    "Reason Generator Reloaded"
)

Reason Generator Reloaded

In [438]:
submission_rows = []

for rank, row in enumerate(
    top100,
    start=1
):

    candidate = row["candidate"]

    reason = (
        reason_generator.generate(

            candidate,

            row["role_score"],

            row["evidence_score"],

            row["signal_score"]
        )
    )

    submission_rows.append({

    "rank": rank,

    "candidate_id": candidate["candidate_id"],

    "score": round(row["final_score"], 2),

    "reasoning": reason
})

submission_df = pd.DataFrame(
    submission_rows
)

print(
    submission_df.head(10)
)

   rank  candidate_id   score  \
0     1  CAND_0055992  407.24
1     2  CAND_0079387  405.28
2     3  CAND_0005649  405.28
3     4  CAND_0044883  404.48
4     5  CAND_0069905  398.37
5     6  CAND_0030953  398.19
6     7  CAND_0044855  382.86
7     8  CAND_0083307  382.80
8     9  CAND_0028793  380.33
9    10  CAND_0013613  379.36

                                           reasoning
0  16.9 years experience. background as AI Engine...
1  6.9 years experience. background as AI Enginee...
2  7.4 years experience. background as Senior Dat...
3  6.3 years experience. background as AI Enginee...
4  6.6 years experience. background as Applied ML...
5  7.8 years experience. background as Search Eng...
6  6.6 years experience. background as Senior Dat...
7  7.8 years experience. background as Search Eng...
8  7.2 years experience. background as Search Eng...
9  4.7 years experience. background as Machine Le...

In [439]:
submission_df = pd.DataFrame(submission_rows)

print(submission_df.head())
print(submission_df.shape)

   rank  candidate_id   score  \
0     1  CAND_0055992  407.24
1     2  CAND_0079387  405.28
2     3  CAND_0005649  405.28
3     4  CAND_0044883  404.48
4     5  CAND_0069905  398.37

                                           reasoning
0  16.9 years experience. background as AI Engine...
1  6.9 years experience. background as AI Enginee...
2  7.4 years experience. background as Senior Dat...
3  6.3 years experience. background as AI Enginee...
4  6.6 years experience. background as Applied ML...
(100, 4)

In [440]:
print(submission_df.isnull().sum())

rank            0
candidate_id    0
score           0
reasoning       0
dtype: int64

In [310]:
submission_df.to_csv(

    "top100_submission_v2.csv",

    index=False
)

print(
    "top100_submission_v2.csv saved"
)

top100_submission_v2.csv saved

In [441]:
submission_df.iloc[0]["reasoning"]

'16.9 years experience. background as AI Engineer. experience with Information Retrieval, MLflow, FAISS. strong role alignment. strong AI/ML evidence. strong recruiter signals'

In [442]:
print(submission_df.isnull().sum())

rank            0
candidate_id    0
score           0
reasoning       0
dtype: int64

In [443]:
submission_df.iloc[0]

rank                                                            1
candidate_id                                         CAND_0055992
score                                                      407.24
reasoning       16.9 years experience. background as AI Engine...
Name: 0, dtype: object

In [312]:
submission_df.head(20)

    rank  candidate_id   score
0      1  CAND_0000981  282.35
1      2  CAND_0000705  273.37
2      3  CAND_0000210  260.95
3      4  CAND_0000452  202.56
4      5  CAND_0000200  163.81
5      6  CAND_0000422  314.47
6      7  CAND_0000878  300.59
7      8  CAND_0000665  326.47
8      9  CAND_0000578  286.71
9     10  CAND_0000229  135.97
10    11  CAND_0000852  399.61
11    12  CAND_0000649  181.43
12    13  CAND_0000031  329.87
13    14  CAND_0000682  251.19
14    15  CAND_0000947  213.69
15    16  CAND_0000944  320.49
16    17  CAND_0000273  283.51
17    18  CAND_0000970  300.64
18    19  CAND_0000508  167.81
19    20  CAND_0000343  400.54

In [313]:
submission_df.describe()

             rank       score
count  100.000000  100.000000
mean    50.500000  164.480500
std     29.011492  104.943096
min      1.000000   19.340000
25%     25.750000   66.960000
50%     50.500000  150.710000
75%     75.250000  253.950000
max    100.000000  417.280000

In [314]:
candidate = top100[0]["candidate"]

print(candidate.keys())

dict_keys(['candidate_id', 'headline', 'summary', 'location', 'country', 'years_experience', 'current_title', 'current_company', 'company_size', 'industry', 'skill_names', 'skill_text', 'num_skills', 'certification_names', 'num_certifications', 'education_tier', 'has_relevant_degree', 'highest_degree', 'profile_score', 'open_to_work', 'response_rate', 'avg_response_time', 'profile_views', 'applications', 'github_score', 'search_appearance', 'saved_by_recruiters', 'interview_completion', 'offer_acceptance', 'connection_count', 'endorsements', 'notice_period_days', 'preferred_work_mode', 'willing_to_relocate', 'verified_email', 'verified_phone', 'linkedin_connected', 'skill_assessment_avg', 'skill_assessment_count', 'days_since_active', 'candidate_text', 'current_role', 'total_duration_months', 'num_companies', 'industries', 'job_titles', 'experience_text', 'career_growth_score'])

In [315]:
for row in top100[:20]:

    c = row["candidate"]

    print("=" * 80)

    print(
        c["candidate_id"]
    )

    print(
        "Experience:",
        c["years_experience"]
    )

    print(
        "Companies:",
        c["num_companies"]
    )

    print(
        "Skills:",
        c["num_skills"]
    )

    print(
        "Certifications:",
        c["num_certifications"]
    )

    print(
        "Growth:",
        c["career_growth_score"]
    )

    print(
        "Titles:",
        c["job_titles"]
    )

================================================================================
CAND_0000981
Experience: 6.4
Companies: 2
Skills: 14
Certifications: 0
Growth: 1
Titles: ['ML Engineer', 'Senior Software Engineer (ML)']
================================================================================
CAND_0000705
Experience: 3.6
Companies: 2
Skills: 15
Certifications: 0
Growth: 0
Titles: ['AI Research Engineer', 'Junior ML Engineer']
================================================================================
CAND_0000210
Experience: 6.3
Companies: 3
Skills: 11
Certifications: 0
Growth: 1
Titles: ['Senior Data Engineer', 'Backend Engineer', 'Data Engineer']
================================================================================
CAND_0000452
Experience: 2.9
Companies: 2
Skills: 11
Certifications: 0
Growth: 2
Titles: ['Senior Data Engineer', 'Senior Data Engineer']
================================================================================
CAND_0000200
Experience: 4.3
Companies: 2
Skills: 12
Certifications: 2
Growth: 0
Titles: ['ML Engineer', 'AI Specialist']
================================================================================
CAND_0000422
Experience: 6.3
Companies: 3
Skills: 11
Certifications: 2
Growth: 0
Titles: ['AI Research Engineer', 'Data Scientist', 'Data Scientist']
================================================================================
CAND_0000878
Experience: 6.9
Companies: 2
Skills: 13
Certifications: 0
Growth: 0
Titles: ['Backend Engineer', 'Software Engineer']
================================================================================
CAND_0000665
Experience: 6.2
Companies: 3
Skills: 10
Certifications: 1
Growth: 2
Titles: ['Senior Software Engineer', 'Senior Software Engineer', 'Backend Engineer']
================================================================================
CAND_0000578
Experience: 6.9
Companies: 2
Skills: 14
Certifications: 0
Growth: 1
Titles: ['Data Engineer', 'Senior Software Engineer']
================================================================================
CAND_0000229
Experience: 2.2
Companies: 1
Skills: 12
Certifications: 0
Growth: 1
Titles: ['Senior Software Engineer']
================================================================================
CAND_0000852
Experience: 4.8
Companies: 3
Skills: 11
Certifications: 0
Growth: 1
Titles: ['Senior Software Engineer', 'Analytics Engineer', 'Data Engineer']
================================================================================
CAND_0000649
Experience: 4.5
Companies: 2
Skills: 12
Certifications: 0
Growth: 0
Titles: ['Data Engineer', 'Data Analyst']
================================================================================
CAND_0000031
Experience: 6.0
Companies: 4
Skills: 17
Certifications: 0
Growth: 0
Titles: ['Recommendation Systems Engineer', 'Search Engineer', 'NLP Engineer', 'Applied ML Engineer']
================================================================================
CAND_0000682
Experience: 2.6
Companies: 2
Skills: 10
Certifications: 0
Growth: 0
Titles: ['Data Engineer', 'Analytics Engineer']
================================================================================
CAND_0000947
Experience: 3.8
Companies: 2
Skills: 16
Certifications: 0
Growth: 0
Titles: ['Analytics Engineer', 'Analytics Engineer']
================================================================================
CAND_0000944
Experience: 4.1
Companies: 2
Skills: 15
Certifications: 2
Growth: 1
Titles: ['Senior Software Engineer', 'Backend Engineer']
================================================================================
CAND_0000273
Experience: 5.8
Companies: 2
Skills: 16
Certifications: 0
Growth: 1
Titles: ['ML Engineer', 'Senior Software Engineer (ML)']
================================================================================
CAND_0000970
Experience: 3.0
Companies: 2
Skills: 12
Certifications: 0
Growth: 0
Titles: ['Data Engineer', 'Software Engineer']
================================================================================
CAND_0000508
Experience: 4.6
Companies: 2
Skills: 11
Certifications: 0
Growth: 0
Titles: ['Backend Engineer', 'Data Analyst']
================================================================================
CAND_0000343
Experience: 6.4
Companies: 3
Skills: 11
Certifications: 2
Growth: 1
Titles: ['Analytics Engineer', 'Backend Engineer', 'Senior Data Engineer']

In [316]:
for row in top100[:20]:

    c = row["candidate"]

    print("=" * 80)

    print(c["candidate_id"])

    print(c["current_title"])

    print(c["skill_names"][:10])

================================================================================
CAND_0000981
ML Engineer
['Semantic Search', 'Computer Vision', 'Image Classification', 'SQL', 'Data Science', 'scikit-learn', 'GANs', 'pgvector', 'Pinecone', 'Next.js']
================================================================================
CAND_0000705
AI Research Engineer
['LoRA', 'Elasticsearch', 'OpenCV', 'GANs', 'TTS', 'RAG', 'Data Science', 'NLP', 'BentoML', 'PEFT']
================================================================================
CAND_0000210
Senior Data Engineer
['Computer Vision', 'Accounting', 'GANs', 'Object Detection', 'Angular', 'Speech Recognition', 'Learning to Rank', 'Statistical Modeling', 'LlamaIndex', 'JavaScript']
================================================================================
CAND_0000452
Senior Data Engineer
['Go', 'SQL', 'Flask', 'Webpack', 'Milvus', 'Reinforcement Learning', 'MLflow', 'Sentence Transformers', 'LlamaIndex', 'Photoshop']
================================================================================
CAND_0000200
ML Engineer
['BigQuery', 'Vector Search', 'Prompt Engineering', 'BentoML', 'LlamaIndex', 'FAISS', 'RAG', 'Object Detection', 'Kubernetes', 'TTS']
================================================================================
CAND_0000422
AI Research Engineer
['MLflow', 'Python', 'Photoshop', 'Milvus', 'Java', 'OpenCV', 'Learning to Rank', 'OpenSearch', 'CNN', 'YOLO']
================================================================================
CAND_0000878
Backend Engineer
['Kubeflow', 'Feature Engineering', 'Tally', 'CNN', 'SEO', 'OpenCV', 'Image Classification', 'Marketing', 'Forecasting', 'LLMs']
================================================================================
CAND_0000665
Senior Software Engineer
['Recommendation Systems', 'CSS', 'Object Detection', 'NLP', 'FastAPI', 'Excel', 'Embeddings', 'Illustrator', 'MLOps', 'ASR']
================================================================================
CAND_0000578
Data Engineer
['HTML', 'Speech Recognition', 'Node.js', 'gRPC', 'Fine-tuning LLMs', 'Kubeflow', 'Agile', 'TensorFlow', 'Forecasting', 'NLP']
================================================================================
CAND_0000229
Senior Software Engineer
['Statistical Modeling', 'Sales', 'Object Detection', 'Deep Learning', 'Computer Vision', 'FastAPI', 'MLflow', 'Kubeflow', 'Recommendation Systems', 'ASR']
================================================================================
CAND_0000852
Senior Software Engineer
['Hadoop', 'Weights & Biases', 'Kubeflow', 'Statistical Modeling', 'Node.js', 'Diffusion Models', 'Agile', 'Flask', 'Time Series', 'MLflow']
================================================================================
CAND_0000649
Data Engineer
['Airflow', 'Elasticsearch', 'Statistical Modeling', 'Databricks', 'Milvus', 'Object Detection', 'Learning to Rank', 'OpenCV', 'Pinecone', 'Tailwind']
================================================================================
CAND_0000031
Recommendation Systems Engineer
['Go', 'MLflow', 'FAISS', 'Pinecone', 'Angular', 'Image Classification', 'Machine Learning', 'Speech Recognition', 'BentoML', 'MLOps']
================================================================================
CAND_0000682
Data Engineer
['Kubeflow', 'MLOps', 'dbt', 'Airflow', 'ASR', 'YOLO', 'Object Detection', 'Time Series', 'gRPC', 'Elasticsearch']
================================================================================
CAND_0000947
Analytics Engineer
['Kafka', 'Statistical Modeling', 'Weaviate', 'SQL', 'Agile', 'MLOps', 'Hugging Face Transformers', 'Node.js', 'Reinforcement Learning', 'Object Detection']
================================================================================
CAND_0000944
Senior Software Engineer
['LangChain', 'Redux', 'JavaScript', 'CNN', 'Image Classification', 'Django', 'scikit-learn', 'GCP', 'Terraform', 'Recommendation Systems']
================================================================================
CAND_0000273
ML Engineer
['TTS', 'Forecasting', 'Spring Boot', 'Fine-tuning LLMs', 'Feature Engineering', 'Diffusion Models', 'Redis', 'Qdrant', 'Project Management', 'LlamaIndex']
================================================================================
CAND_0000970
Data Engineer
['MLflow', 'TypeScript', 'Semantic Search', 'Data Pipelines', 'Time Series', 'PyTorch', 'Speech Recognition', 'Figma', 'FAISS', 'ASR']
================================================================================
CAND_0000508
Backend Engineer
['Forecasting', 'Docker', 'Kubernetes', 'MLflow', 'Spark', 'Agile', 'OpenSearch', 'TTS', 'Haystack', 'Computer Vision']
================================================================================
CAND_0000343
Analytics Engineer
['Speech Recognition', 'Diffusion Models', 'REST APIs', 'Machine Learning', 'Weaviate', 'Agile', 'MLflow', 'Milvus', 'MongoDB', 'Kubernetes']

In [317]:
candidate = top100[0]["candidate"]

print(candidate["experience_text"])

ML Engineer HealthTech AI Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranking over engagement signals. Pure ML side of the work; production deployment was handled by the platform team. Senior Software Engineer (ML) SaaS Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.

In [318]:
top100[1]
top100[2]
top100[3]
top100[4]

{'candidate': {'candidate_id': 'CAND_0000200',
  'headline': 'ML Engineer | Data Science & ML enthusiast',
  'summary': "Data scientist / ML engineer with 4.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level.",
  'location': 'Indore, Madhya Pradesh',
  'country': 'India',
  'years_experience': 4.3,
  'current_title': 'ML Engineer',
  'current_company': 'Aganitha',
  'company_size': '51-200',
  'industry': 'AI/ML',
  'skill_names': ['BigQuery',
   'Vector Search',
   'Prompt Engineering',
   'BentoML',
   'LlamaIndex',
   'FAISS',
   'RAG',
   'Object Detection',
   'Kubernetes',
   'TTS',
   'Kubeflow',
   'Apache Flink'],
  'skill_text': 'BigQuery Vector Search Prompt Engineering BentoML LlamaIndex FAISS RAG Object Detection Kubernetes TTS Kubeflow Apache Flink',
  'num_skills': 12,
  'certification_names': ['Google Cloud Professional ML Engineer',
   'NLP Specialization'],
  'num_certifications': 2,
  'education_tier': 'tier_3',
  'has_relevant_degree': 1,
  'highest_degree': 'M.S.',
  'profile_score': 52.7,
  'open_to_work': 1,
  'response_rate': 0.6000000000000001,
  'avg_response_time': 58.5,
  'profile_views': 220,
  'applications': 16,
  'github_score': -1,
  'search_appearance': 629,
  'saved_by_recruiters': 40,
  'interview_completion': 0.99,
  'offer_acceptance': -1,
  'connection_count': 1096,
  'endorsements': 36,
  'notice_period_days': 90,
  'preferred_work_mode': 'remote',
  'willing_to_relocate': 1,
  'verified_email': 1,
  'verified_phone': 1,
  'linkedin_connected': 0,
  'skill_assessment_avg': 52.6,
  'skill_assessment_count': 1,
  'days_since_active': 52,
  'candidate_text': "ML Engineer ML Engineer | Data Science & ML enthusiast Data scientist / ML engineer with 4.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at the modeling and analysis side; comfortable with Python, scikit-learn, pandas, and standard MLOps tooling, but I'm still building depth on the engineering and infra side of production ML. I want to grow into senior AI engineering — get serious about LLMs and retrieval beyond the surface level. BigQuery Vector Search Prompt Engineering BentoML LlamaIndex FAISS RAG Object Detection Kubernetes TTS Kubeflow Apache Flink Google Cloud Professional ML Engineer NLP Specialization",
  'current_role': 'ML Engineer',
  'total_duration_months': 51,
  'num_companies': 2,
  'industries': ['AI/ML', 'Food Delivery'],
  'job_titles': ['ML Engineer', 'AI Specialist'],
  'experience_text': 'ML Engineer AI/ML Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling and data prep / SQL. The churn model is now used by the retention team, though my role was more on the modeling side than the productionization. AI Specialist Food Delivery Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.',
  'career_growth_score': 0},
 'final_score': 163.81}

In [319]:
print(
    top100[0]["candidate"]["skill_names"]
)

print()

print(
    top100[0]["candidate"]["experience_text"]
)

['Semantic Search', 'Computer Vision', 'Image Classification', 'SQL', 'Data Science', 'scikit-learn', 'GANs', 'pgvector', 'Pinecone', 'Next.js', 'Airflow', 'OpenSearch', 'MLflow', 'OpenCV']

ML Engineer HealthTech AI Built recommendation-style features at a mid-stage startup — lighter weight than ranking systems at FAANG, but production. Used a combination of collaborative filtering (matrix factorization in implicit-feedback library) and gradient-boosted re-ranking over engagement signals. Pure ML side of the work; production deployment was handled by the platform team. Senior Software Engineer (ML) SaaS Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.

In [320]:
print(
    top100[1]["candidate"]["skill_names"]
)

print()

print(
    top100[1]["candidate"]["experience_text"]
)

['LoRA', 'Elasticsearch', 'OpenCV', 'GANs', 'TTS', 'RAG', 'Data Science', 'NLP', 'BentoML', 'PEFT', 'Statistical Modeling', 'Computer Vision', 'Haystack', 'Diffusion Models', 'Redis']

AI Research Engineer Food Delivery Built computer vision models for our product's image moderation feature using PyTorch — fine-tuned ResNet variants on a labeled dataset of ~200K images. Set up the training pipeline (data loading, augmentation, evaluation) and the inference service. Most of my project work has been in CV; I'm now interested in transitioning toward NLP/LLM work but my professional experience there is limited. Junior ML Engineer E-commerce Worked on time-series forecasting models for supply-chain demand prediction at a logistics company. Built models in Prophet, LightGBM, and (for one project) a small LSTM — the LightGBM model ended up shipping. Also ran some reinforcement learning experiments for dynamic pricing but those didn't make it to production. The work was a mix of modeling, analysis, and stakeholder communication with the operations team.

In [321]:
print(
    top100[2]["candidate"]["skill_names"]
)

print()

print(
    top100[2]["candidate"]["experience_text"]
)

['Computer Vision', 'Accounting', 'GANs', 'Object Detection', 'Angular', 'Speech Recognition', 'Learning to Rank', 'Statistical Modeling', 'LlamaIndex', 'JavaScript', 'LangChain']

Senior Data Engineer EdTech Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as performance optimization (query tuning, cluster sizing, materialized views). Also built the lineage and documentation framework now in use across the data org. Backend Engineer Manufacturing Backend + data hybrid role at a growth-stage startup. Built the company's first proper data warehouse (migrating from a tangled set of Postgres replicas to a clean Snowflake setup with dbt), the orchestration layer (Airflow), and the BI integration (Looker). Shipped a couple of small predictive features but the bulk of the role was data infrastructure. Data Engineer Fintech Designed and maintained the analytical data warehouse on Snowflake supporting the BI team's ~50 dashboards. Wrote complex SQL — heavy on window functions, CTEs, and incremental modeling patterns via dbt. Worked on the data modeling side (dimensional modeling, slowly changing dimensions) as well as performance optimization (query tuning, cluster sizing, materialized views). Also built the lineage and documentation framework now in use across the data org.

In [322]:
print(
    top100[3]["candidate"]["skill_names"]
)

print()

print(
    top100[3]["candidate"]["experience_text"]
)

['Go', 'SQL', 'Flask', 'Webpack', 'Milvus', 'Reinforcement Learning', 'MLflow', 'Sentence Transformers', 'LlamaIndex', 'Photoshop', 'TTS']

Senior Data Engineer IT Services Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models. Senior Data Engineer Conglomerate Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.

In [323]:
print(
    top100[4]["candidate"]["skill_names"]
)

print()

print(
    top100[4]["candidate"]["experience_text"]
)

['BigQuery', 'Vector Search', 'Prompt Engineering', 'BentoML', 'LlamaIndex', 'FAISS', 'RAG', 'Object Detection', 'Kubernetes', 'TTS', 'Kubeflow', 'Apache Flink']

ML Engineer AI/ML Worked on customer-facing predictive modeling for an e-commerce platform — churn prediction, conversion likelihood, lifetime value estimation. Used scikit-learn and XGBoost; main models were gradient-boosted trees with ~80 hand-engineered features. The work was split roughly 60/40 between modeling and data prep / SQL. The churn model is now used by the retention team, though my role was more on the modeling side than the productionization. AI Specialist Food Delivery Built NLP pipelines for sentiment analysis and document classification — primarily for an internal feedback-analytics dashboard. Started with sklearn-based bag-of-words models, then moved to transformer-based classifiers (DistilBERT) for the harder classes. Comfortable with PyTorch and Hugging Face but most of my training experience has been on small datasets and pre-trained model fine-tuning, not from-scratch model design.

In [324]:
target_terms = [

    "recommendation",
    "ranking",
    "retrieval",
    "search",
    "embedding",
    "embeddings",
    "nlp",
    "llm",
    "transformer",
    "rag",
    "airflow",
    "spark",
    "faiss",
    "pinecone",
    "milvus"
]

for row in top100[:20]:

    c = row["candidate"]

    text = c["experience_text"].lower()

    matches = []

    for term in target_terms:

        if term in text:

            matches.append(term)

    print("=" * 80)

    print(c["candidate_id"])

    print(c["current_title"])

    print("Evidence Terms:", matches)

================================================================================
CAND_0000981
ML Engineer
Evidence Terms: ['recommendation', 'ranking', 'nlp', 'transformer']
================================================================================
CAND_0000705
AI Research Engineer
Evidence Terms: ['search', 'nlp', 'llm']
================================================================================
CAND_0000210
Senior Data Engineer
Evidence Terms: ['airflow']
================================================================================
CAND_0000452
Senior Data Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000200
ML Engineer
Evidence Terms: ['nlp', 'transformer']
================================================================================
CAND_0000422
AI Research Engineer
Evidence Terms: ['recommendation', 'ranking', 'search', 'nlp', 'transformer']
================================================================================
CAND_0000878
Backend Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000665
Senior Software Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000578
Data Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000229
Senior Software Engineer
Evidence Terms: []
================================================================================
CAND_0000852
Senior Software Engineer
Evidence Terms: ['spark']
================================================================================
CAND_0000649
Data Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000031
Recommendation Systems Engineer
Evidence Terms: ['recommendation', 'ranking', 'search', 'nlp']
================================================================================
CAND_0000682
Data Engineer
Evidence Terms: []
================================================================================
CAND_0000947
Analytics Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000944
Senior Software Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000273
ML Engineer
Evidence Terms: ['recommendation', 'ranking']
================================================================================
CAND_0000970
Data Engineer
Evidence Terms: ['airflow', 'spark']
================================================================================
CAND_0000508
Backend Engineer
Evidence Terms: ['spark']
================================================================================
CAND_0000343
Analytics Engineer
Evidence Terms: ['airflow', 'spark']

In [325]:
for row in ranked_candidates[:20]:

    c = row["candidate"]

    print("=" * 80)

    print(c["current_title"])

    print("Final:", row["final_score"])

    print("Role:", row["role_score"])

    print("Evidence:", row["evidence_score"])

    print("Signal:", row["signal_score"])

    print("Integrity:", row["integrity_score"])

================================================================================
ML Engineer
Final: 282.35

KeyError: 'role_score'

In [326]:
from collections import Counter

titles = []

for row in ranked_candidates[:100]:

    titles.append(
        row["candidate"]["current_title"]
    )

Counter(titles).most_common(20)

[('Software Engineer', 18),
 ('Frontend Engineer', 18),
 ('Backend Engineer', 9),
 ('Cloud Engineer', 9),
 ('Analytics Engineer', 8),
 ('QA Engineer', 8),
 ('Senior Software Engineer', 7),
 ('Data Engineer', 6),
 ('ML Engineer', 3),
 ('Senior Data Engineer', 3),
 ('AI Specialist', 3),
 ('AI Research Engineer', 2),
 ('Data Analyst', 2),
 ('DevOps Engineer', 2),
 ('Recommendation Systems Engineer', 1),
 ('Data Scientist', 1)]

In [327]:
ai_titles = [

    "ML Engineer",
    "AI Research Engineer",
    "AI Specialist",
    "Data Scientist",
    "Recommendation Systems Engineer"
]

backend_titles = [

    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Senior Software Engineer"
]

ai_count = 0
backend_count = 0

for row in ranked_candidates[:100]:

    title = row["candidate"]["current_title"]

    if title in ai_titles:
        ai_count += 1

    if title in backend_titles:
        backend_count += 1

print("AI:", ai_count)
print("Backend/Data:", backend_count)

AI: 10
Backend/Data: 48

In [328]:
for row in ranked_candidates[:30]:

    title = row["candidate"]["current_title"]

    if title in [

        "AI Research Engineer",
        "ML Engineer",
        "Recommendation Systems Engineer",
        "Data Scientist",
        "AI Specialist"
    ]:

        print("=" * 80)

        print(title)

        print("Final:", row["final_score"])

        print("Evidence:", row["evidence_score"])

        print("Role:", row["role_score"])

================================================================================
ML Engineer
Final: 282.35

KeyError: 'evidence_score'

In [329]:
from importlib import reload

import src.role_intelligence

reload(
    src.role_intelligence
)

from src.role_intelligence import (
    RoleIntelligenceEngine
)

role_engine = (
    RoleIntelligenceEngine()
)

print(
    "Role Engine Reloaded"
)

Role Engine Reloaded

In [330]:
# ==========================
# Build Retrieval Query
# ==========================

retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
AI Research Engineer
Recommendation Systems Engineer
Search Engineer
Relevance Engineer

Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Search
Recommendation

Embeddings
Vector Database
Pinecone
Milvus
FAISS
Qdrant

Python
Spark
Airflow

Learning To Rank
NDCG
MRR

Production ML
Feature Engineering

5-9 years experience
"""

# ==========================
# Encode Query
# ==========================

jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

# ==========================
# Retrieve Top 1000
# ==========================

scores, indices = index.search(

    jd_embedding.reshape(
        1,
        -1
    ).astype(
        "float32"
    ),

    1000
)

print(
    "Retrieved:",
    len(indices[0])
)

Retrieved: 1000

In [331]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = (
        role_engine.score(
            candidate
        )
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = (
        ranker.score(

            semantic_score=
                semantic_score,

            role_score=
                role_score,

            evidence_score=
                evidence_score,

            signal_score=
                signal_score,

            integrity_score=
                integrity_score
        )
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    "Ranked:",
    len(
        ranked_candidates
    )
)

Ranked: 1000

In [332]:
top100 = ranked_candidates[:100]

print(
    "Top100:",
    len(top100)
)

Top100: 100

In [333]:
from collections import Counter

titles = []

for row in top100:

    titles.append(

        row["candidate"][
            "current_title"
        ]
    )

print()

print(
    Counter(
        titles
    ).most_common(25)
)

[('Software Engineer', 40), ('Backend Engineer', 9), ('Analytics Engineer', 8), ('Senior Software Engineer', 7), ('Data Engineer', 6), ('Java Developer', 6), ('Senior Data Engineer', 3), ('AI Specialist', 3), ('ML Engineer', 3), ('Data Analyst', 3), ('Cloud Engineer', 3), ('DevOps Engineer', 3), ('AI Research Engineer', 2), ('Full Stack Developer', 2), ('Recommendation Systems Engineer', 1), ('Data Scientist', 1)]

In [334]:
ai_titles = [

    "ML Engineer",
    "AI Research Engineer",
    "AI Specialist",
    "Data Scientist",
    "Recommendation Systems Engineer"
]

backend_titles = [

    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Senior Software Engineer"
]

ai_count = 0
backend_count = 0

for row in top100:

    title = row["candidate"][
        "current_title"
    ]

    if title in ai_titles:

        ai_count += 1

    if title in backend_titles:

        backend_count += 1

print(
    "AI:",
    ai_count
)

print(
    "Backend/Data:",
    backend_count
)

AI: 10
Backend/Data: 70

In [335]:
for row in ranked_candidates[:20]:

    c = row["candidate"]

    print(
        "=" * 80
    )

    print(
        c["current_title"]
    )

    print(
        "Final:",
        row["final_score"]
    )

    print(
        "Role:",
        row["role_score"]
    )

    print(
        "Evidence:",
        row["evidence_score"]
    )

    print(
        "Signal:",
        row["signal_score"]
    )

    print(
        "Integrity:",
        row["integrity_score"]
    )

================================================================================
Recommendation Systems Engineer
Final: 290.2
Role: 160
Evidence: 29
Signal: 69.36
Integrity: 100
================================================================================
Senior Software Engineer
Final: 286.42
Role: 160
Evidence: 28
Signal: 68.44
Integrity: 100
================================================================================
Data Scientist
Final: 277.3
Role: 160
Evidence: 27
Signal: 56.83
Integrity: 100
================================================================================
AI Research Engineer
Final: 274.56
Role: 160
Evidence: 24
Signal: 68.33
Integrity: 100
================================================================================
Senior Software Engineer
Final: 265.81
Role: 160
Evidence: 26
Signal: 40.26
Integrity: 100
================================================================================
Software Engineer
Final: 261.55
Role: 160
Evidence: 27
Signal: 25.68
Integrity: 100
================================================================================
Software Engineer
Final: 260.66
Role: 160
Evidence: 21
Signal: 59.13
Integrity: 100
================================================================================
Analytics Engineer
Final: 260.42
Role: 160
Evidence: 22
Signal: 52.83
Integrity: 100
================================================================================
Senior Software Engineer
Final: 260.24
Role: 140
Evidence: 28
Signal: 56.69
Integrity: 100
================================================================================
Senior Software Engineer
Final: 259.48
Role: 160
Evidence: 24
Signal: 38.76
Integrity: 100
================================================================================
Backend Engineer
Final: 257.77
Role: 140
Evidence: 28
Signal: 52.23
Integrity: 100
================================================================================
Software Engineer
Final: 254.63
Role: 140
Evidence: 27
Signal: 51.96
Integrity: 100
================================================================================
Analytics Engineer
Final: 253.64
Role: 140
Evidence: 27
Signal: 49.03
Integrity: 100
================================================================================
Analytics Engineer
Final: 248.59
Role: 160
Evidence: 18
Signal: 53.72
Integrity: 100
================================================================================
Analytics Engineer
Final: 244.98
Role: 140
Evidence: 24
Signal: 50.13
Integrity: 100
================================================================================
Senior Data Engineer
Final: 242.42
Role: 140
Evidence: 27
Signal: 26.46
Integrity: 100
================================================================================
Data Engineer
Final: 240.63
Role: 140
Evidence: 21
Signal: 58.99
Integrity: 100
================================================================================
Backend Engineer
Final: 240.48
Role: 140
Evidence: 22
Signal: 52.67
Integrity: 100
================================================================================
AI Specialist
Final: 237.58
Role: 140
Evidence: 18
Signal: 71.08
Integrity: 100
================================================================================
Software Engineer
Final: 236.86
Role: 160
Evidence: 18
Signal: 29.86
Integrity: 100

In [336]:
from importlib import reload

import src.role_intelligence

reload(
    src.role_intelligence
)

from src.role_intelligence import (
    RoleIntelligenceEngine
)

role_engine = (
    RoleIntelligenceEngine()
)

print(
    "Role Engine Reloaded"
)

Role Engine Reloaded

In [337]:
retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
AI Research Engineer
Recommendation Systems Engineer
Search Engineer
Relevance Engineer

Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Search
Recommendation

Embeddings
Vector Database
Pinecone
Milvus
FAISS
Qdrant

Python
Spark
Airflow

Learning To Rank
NDCG
MRR

Production ML
Feature Engineering

5-9 years experience
"""

jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

scores, indices = index.search(

    jd_embedding.reshape(
        1,
        -1
    ).astype(
        "float32"
    ),

    1000
)

print(
    "Retrieved:",
    len(indices[0])
)

Retrieved: 1000

In [338]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = (
        role_engine.score(
            candidate
        )
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = (
        ranker.score(

            semantic_score=
                semantic_score,

            role_score=
                role_score,

            evidence_score=
                evidence_score,

            signal_score=
                signal_score,

            integrity_score=
                integrity_score
        )
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(
        ranked_candidates
    )
)

1000

In [339]:
top100 = ranked_candidates[:100]

print(
    len(top100)
)

100

In [340]:
ai_titles = [

    "ML Engineer",
    "AI Research Engineer",
    "AI Specialist",
    "Data Scientist",
    "Recommendation Systems Engineer"
]

backend_titles = [

    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Senior Software Engineer"
]

ai_count = 0
backend_count = 0

for row in top100:

    title = row["candidate"][
        "current_title"
    ]

    if title in ai_titles:

        ai_count += 1

    if title in backend_titles:

        backend_count += 1

print(
    "AI:",
    ai_count
)

print(
    "Backend/Data:",
    backend_count
)

AI: 10
Backend/Data: 70

In [341]:
from collections import Counter

titles = []

for row in top100:

    titles.append(

        row["candidate"][
            "current_title"
        ]
    )

print(
    Counter(
        titles
    ).most_common(25)
)

[('Software Engineer', 40), ('Backend Engineer', 9), ('Analytics Engineer', 8), ('Senior Software Engineer', 7), ('Data Engineer', 6), ('Java Developer', 6), ('Senior Data Engineer', 3), ('AI Specialist', 3), ('ML Engineer', 3), ('Data Analyst', 3), ('Cloud Engineer', 3), ('DevOps Engineer', 3), ('AI Research Engineer', 2), ('Full Stack Developer', 2), ('Recommendation Systems Engineer', 1), ('Data Scientist', 1)]

In [342]:
for row in ranked_candidates[:20]:

    c = row["candidate"]

    print(
        "=" * 80
    )

    print(
        c["current_title"]
    )

    print(
        "Final:",
        row["final_score"]
    )

    print(
        "Role:",
        row["role_score"]
    )

    print(
        "Evidence:",
        row["evidence_score"]
    )

    print(
        "Signal:",
        row["signal_score"]
    )

    print(
        "Integrity:",
        row["integrity_score"]
    )

================================================================================
Recommendation Systems Engineer
Final: 290.2
Role: 160
Evidence: 29
Signal: 69.36
Integrity: 100
================================================================================
Senior Software Engineer
Final: 286.42
Role: 160
Evidence: 28
Signal: 68.44
Integrity: 100
================================================================================
Data Scientist
Final: 277.3
Role: 160
Evidence: 27
Signal: 56.83
Integrity: 100
================================================================================
AI Research Engineer
Final: 274.56
Role: 160
Evidence: 24
Signal: 68.33
Integrity: 100
================================================================================
Senior Software Engineer
Final: 265.81
Role: 160
Evidence: 26
Signal: 40.26
Integrity: 100
================================================================================
Software Engineer
Final: 261.55
Role: 160
Evidence: 27
Signal: 25.68
Integrity: 100
================================================================================
Software Engineer
Final: 260.66
Role: 160
Evidence: 21
Signal: 59.13
Integrity: 100
================================================================================
Analytics Engineer
Final: 260.42
Role: 160
Evidence: 22
Signal: 52.83
Integrity: 100
================================================================================
Senior Software Engineer
Final: 260.24
Role: 140
Evidence: 28
Signal: 56.69
Integrity: 100
================================================================================
Senior Software Engineer
Final: 259.48
Role: 160
Evidence: 24
Signal: 38.76
Integrity: 100
================================================================================
Backend Engineer
Final: 257.77
Role: 140
Evidence: 28
Signal: 52.23
Integrity: 100
================================================================================
Software Engineer
Final: 254.63
Role: 140
Evidence: 27
Signal: 51.96
Integrity: 100
================================================================================
Analytics Engineer
Final: 253.64
Role: 140
Evidence: 27
Signal: 49.03
Integrity: 100
================================================================================
Analytics Engineer
Final: 248.59
Role: 160
Evidence: 18
Signal: 53.72
Integrity: 100
================================================================================
Analytics Engineer
Final: 244.98
Role: 140
Evidence: 24
Signal: 50.13
Integrity: 100
================================================================================
Senior Data Engineer
Final: 242.42
Role: 140
Evidence: 27
Signal: 26.46
Integrity: 100
================================================================================
Data Engineer
Final: 240.63
Role: 140
Evidence: 21
Signal: 58.99
Integrity: 100
================================================================================
Backend Engineer
Final: 240.48
Role: 140
Evidence: 22
Signal: 52.67
Integrity: 100
================================================================================
AI Specialist
Final: 237.58
Role: 140
Evidence: 18
Signal: 71.08
Integrity: 100
================================================================================
Software Engineer
Final: 236.86
Role: 160
Evidence: 18
Signal: 29.86
Integrity: 100

In [343]:
for row in ranked_candidates[:20]:

    print(
        row["candidate"]["current_title"],
        "|",
        "Role:",
        row["role_score"],
        "|",
        "Evidence:",
        row["evidence_score"],
        "|",
        "Final:",
        row["final_score"]
    )

Recommendation Systems Engineer | Role: 160 | Evidence: 29 | Final: 290.2
Senior Software Engineer | Role: 160 | Evidence: 28 | Final: 286.42
Data Scientist | Role: 160 | Evidence: 27 | Final: 277.3
AI Research Engineer | Role: 160 | Evidence: 24 | Final: 274.56
Senior Software Engineer | Role: 160 | Evidence: 26 | Final: 265.81
Software Engineer | Role: 160 | Evidence: 27 | Final: 261.55
Software Engineer | Role: 160 | Evidence: 21 | Final: 260.66
Analytics Engineer | Role: 160 | Evidence: 22 | Final: 260.42
Senior Software Engineer | Role: 140 | Evidence: 28 | Final: 260.24
Senior Software Engineer | Role: 160 | Evidence: 24 | Final: 259.48
Backend Engineer | Role: 140 | Evidence: 28 | Final: 257.77
Software Engineer | Role: 140 | Evidence: 27 | Final: 254.63
Analytics Engineer | Role: 140 | Evidence: 27 | Final: 253.64
Analytics Engineer | Role: 160 | Evidence: 18 | Final: 248.59
Analytics Engineer | Role: 140 | Evidence: 24 | Final: 244.98
Senior Data Engineer | Role: 140 | Evidence: 27 | Final: 242.42
Data Engineer | Role: 140 | Evidence: 21 | Final: 240.63
Backend Engineer | Role: 140 | Evidence: 22 | Final: 240.48
AI Specialist | Role: 140 | Evidence: 18 | Final: 237.58
Software Engineer | Role: 160 | Evidence: 18 | Final: 236.86

In [346]:
from src.ai_bonus import (
    AIBonusEngine
)

ai_bonus_engine = (
    AIBonusEngine()
)

In [347]:
ai_bonus_score = (
    ai_bonus_engine.score(
        candidate
    )
)

In [348]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = (
        role_engine.score(
            candidate
        )
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    ai_bonus_score = (
        ai_bonus_engine.score(
            candidate
        )
    )

    final_score = (

        ranker.score(

            semantic_score,

            role_score,

            evidence_score,

            signal_score,

            integrity_score

        )

        +

        ai_bonus_score
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "ai_bonus_score":
            ai_bonus_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(
        ranked_candidates
    )
)

1000

In [349]:
from importlib import reload

import src.integrity_engine

reload(
    src.integrity_engine
)

from src.integrity_engine import (
    IntegrityEngine
)

integrity_engine = (
    IntegrityEngine()
)

print(
    "Integrity Engine Reloaded"
)

Integrity Engine Reloaded

In [350]:
for row in ranked_candidates[:20]:

    print(
        "=" * 80
    )

    print(
        row["candidate"][
            "current_title"
        ]
    )

    print(
        "Role:",
        row["role_score"]
    )

    print(
        "Evidence:",
        row["evidence_score"]
    )

    print(
        "AI Bonus:",
        row["ai_bonus_score"]
    )

    print(
        "Integrity:",
        row["integrity_score"]
    )

    print(
        "Final:",
        row["final_score"]
    )

================================================================================
Recommendation Systems Engineer
Role: 160
Evidence: 29
AI Bonus: 40
Integrity: 100
Final: 330.2
================================================================================
Data Scientist
Role: 160
Evidence: 27
AI Bonus: 30
Integrity: 100
Final: 307.3
================================================================================
AI Research Engineer
Role: 160
Evidence: 24
AI Bonus: 30
Integrity: 100
Final: 304.56
================================================================================
Senior Software Engineer
Role: 160
Evidence: 28
AI Bonus: 0
Integrity: 100
Final: 286.42
================================================================================
Senior Software Engineer
Role: 160
Evidence: 26
AI Bonus: 0
Integrity: 100
Final: 265.81
================================================================================
Software Engineer
Role: 160
Evidence: 27
AI Bonus: 0
Integrity: 100
Final: 261.55
================================================================================
Software Engineer
Role: 160
Evidence: 21
AI Bonus: 0
Integrity: 100
Final: 260.66
================================================================================
Analytics Engineer
Role: 160
Evidence: 22
AI Bonus: 0
Integrity: 100
Final: 260.42
================================================================================
Senior Software Engineer
Role: 140
Evidence: 28
AI Bonus: 0
Integrity: 100
Final: 260.24
================================================================================
Senior Software Engineer
Role: 160
Evidence: 24
AI Bonus: 0
Integrity: 100
Final: 259.48
================================================================================
Backend Engineer
Role: 140
Evidence: 28
AI Bonus: 0
Integrity: 100
Final: 257.77
================================================================================
Software Engineer
Role: 140
Evidence: 27
AI Bonus: 0
Integrity: 100
Final: 254.63
================================================================================
Analytics Engineer
Role: 140
Evidence: 27
AI Bonus: 0
Integrity: 100
Final: 253.64
================================================================================
Analytics Engineer
Role: 160
Evidence: 18
AI Bonus: 0
Integrity: 100
Final: 248.59
================================================================================
Analytics Engineer
Role: 140
Evidence: 24
AI Bonus: 0
Integrity: 100
Final: 244.98
================================================================================
ML Engineer
Role: 140
Evidence: 13
AI Bonus: 20
Integrity: 100
Final: 243.57
================================================================================
Senior Data Engineer
Role: 140
Evidence: 27
AI Bonus: 0
Integrity: 100
Final: 242.42
================================================================================
ML Engineer
Role: 140
Evidence: 19
AI Bonus: 20
Integrity: 100
Final: 242.41
================================================================================
Data Engineer
Role: 140
Evidence: 21
AI Bonus: 0
Integrity: 100
Final: 240.63
================================================================================
Backend Engineer
Role: 140
Evidence: 22
AI Bonus: 0
Integrity: 100
Final: 240.48

In [351]:
ai_titles = [

    "ML Engineer",
    "AI Research Engineer",
    "AI Specialist",
    "Data Scientist",
    "Recommendation Systems Engineer"
]

backend_titles = [

    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Senior Software Engineer"
]

ai_count = 0
backend_count = 0

for row in ranked_candidates[:100]:

    title = row["candidate"][
        "current_title"
    ]

    if title in ai_titles:

        ai_count += 1

    if title in backend_titles:

        backend_count += 1

print(
    "AI:",
    ai_count
)

print(
    "Backend/Data:",
    backend_count
)

AI: 10
Backend/Data: 70

In [352]:
top100 = ranked_candidates[:100]

print(
    len(top100)
)

100

In [353]:
ai_titles = [

    "ML Engineer",
    "AI Research Engineer",
    "AI Specialist",
    "Data Scientist",
    "Recommendation Systems Engineer"
]

backend_titles = [

    "Software Engineer",
    "Backend Engineer",
    "Data Engineer",
    "Analytics Engineer",
    "Senior Software Engineer"
]

ai_count = 0
backend_count = 0

for row in top100:

    title = row["candidate"][
        "current_title"
    ]

    if title in ai_titles:
        ai_count += 1

    if title in backend_titles:
        backend_count += 1

print(
    "AI:",
    ai_count
)

print(
    "Backend/Data:",
    backend_count
)

AI: 10
Backend/Data: 70

In [354]:
for row in ranked_candidates[:20]:

    c = row["candidate"]

    print(
        "=" * 80
    )

    print(
        c["current_title"]
    )

    print(
        "Final:",
        row["final_score"]
    )

    print(
        "Role:",
        row["role_score"]
    )

    print(
        "Evidence:",
        row["evidence_score"]
    )

    print(
        "AI Bonus:",
        row["ai_bonus_score"]
    )

    print(
        "Signal:",
        row["signal_score"]
    )

    print(
        "Integrity:",
        row["integrity_score"]
    )

================================================================================
Recommendation Systems Engineer
Final: 330.2
Role: 160
Evidence: 29
AI Bonus: 40
Signal: 69.36
Integrity: 100
================================================================================
Data Scientist
Final: 307.3
Role: 160
Evidence: 27
AI Bonus: 30
Signal: 56.83
Integrity: 100
================================================================================
AI Research Engineer
Final: 304.56
Role: 160
Evidence: 24
AI Bonus: 30
Signal: 68.33
Integrity: 100
================================================================================
Senior Software Engineer
Final: 286.42
Role: 160
Evidence: 28
AI Bonus: 0
Signal: 68.44
Integrity: 100
================================================================================
Senior Software Engineer
Final: 265.81
Role: 160
Evidence: 26
AI Bonus: 0
Signal: 40.26
Integrity: 100
================================================================================
Software Engineer
Final: 261.55
Role: 160
Evidence: 27
AI Bonus: 0
Signal: 25.68
Integrity: 100
================================================================================
Software Engineer
Final: 260.66
Role: 160
Evidence: 21
AI Bonus: 0
Signal: 59.13
Integrity: 100
================================================================================
Analytics Engineer
Final: 260.42
Role: 160
Evidence: 22
AI Bonus: 0
Signal: 52.83
Integrity: 100
================================================================================
Senior Software Engineer
Final: 260.24
Role: 140
Evidence: 28
AI Bonus: 0
Signal: 56.69
Integrity: 100
================================================================================
Senior Software Engineer
Final: 259.48
Role: 160
Evidence: 24
AI Bonus: 0
Signal: 38.76
Integrity: 100
================================================================================
Backend Engineer
Final: 257.77
Role: 140
Evidence: 28
AI Bonus: 0
Signal: 52.23
Integrity: 100
================================================================================
Software Engineer
Final: 254.63
Role: 140
Evidence: 27
AI Bonus: 0
Signal: 51.96
Integrity: 100
================================================================================
Analytics Engineer
Final: 253.64
Role: 140
Evidence: 27
AI Bonus: 0
Signal: 49.03
Integrity: 100
================================================================================
Analytics Engineer
Final: 248.59
Role: 160
Evidence: 18
AI Bonus: 0
Signal: 53.72
Integrity: 100
================================================================================
Analytics Engineer
Final: 244.98
Role: 140
Evidence: 24
AI Bonus: 0
Signal: 50.13
Integrity: 100
================================================================================
ML Engineer
Final: 243.57
Role: 140
Evidence: 13
AI Bonus: 20
Signal: 72.73
Integrity: 100
================================================================================
Senior Data Engineer
Final: 242.42
Role: 140
Evidence: 27
AI Bonus: 0
Signal: 26.46
Integrity: 100
================================================================================
ML Engineer
Final: 242.41
Role: 140
Evidence: 19
AI Bonus: 20
Signal: 33.75
Integrity: 100
================================================================================
Data Engineer
Final: 240.63
Role: 140
Evidence: 21
AI Bonus: 0
Signal: 58.99
Integrity: 100
================================================================================
Backend Engineer
Final: 240.48
Role: 140
Evidence: 22
AI Bonus: 0
Signal: 52.67
Integrity: 100

In [355]:
from collections import Counter

titles = []

for row in top100:

    titles.append(
        row["candidate"][
            "current_title"
        ]
    )

print(
    Counter(
        titles
    ).most_common(25)
)

[('Software Engineer', 40), ('Backend Engineer', 9), ('Analytics Engineer', 8), ('Senior Software Engineer', 7), ('Data Engineer', 6), ('Java Developer', 6), ('ML Engineer', 3), ('Senior Data Engineer', 3), ('AI Specialist', 3), ('Data Analyst', 3), ('Cloud Engineer', 3), ('DevOps Engineer', 3), ('AI Research Engineer', 2), ('Full Stack Developer', 2), ('Recommendation Systems Engineer', 1), ('Data Scientist', 1)]

In [356]:
import os

for root, dirs, files in os.walk("."):

    for file in files:

        if file.endswith(".ipynb"):

            print(
                os.path.join(
                    root,
                    file
                )
            )

.\01_dataset_understanding.ipynb
.\02_candidate_parser.ipynb
.\03_jd_understanding.ipynb
.\04_semantic_retrieval.ipynb
.\05_signal_engine.ipynb
.\06_ranking_engine.ipynb
.\07_explainability.ipynb
.\08_career_features.ipynb
.\09_jd_intent.ipynb
.\10_embeddings.ipynb
.\11_retrieval.ipynb
.\12_career_match.ipynb
.\13_signals.ipynb
.\14_end_to_end_pipeline.ipynb
.\15_role_intelligence.ipynb
.\16_evidence_match.ipynb
.\99_pipeline_debug.ipynb

In [357]:
import os

for root, dirs, files in os.walk("src"):

    for file in files:

        print(
            os.path.join(
                root,
                file
            )
        )

PHASE 2

In [358]:
retrieval_query = """
Senior AI Engineer
Machine Learning Engineer
AI Engineer
AI Research Engineer

Recommendation Systems Engineer
Search Engineer
Relevance Engineer

Backend Engineer
Data Engineer
Analytics Engineer

Retrieval
Ranking
Recommendation
Search

Embeddings
Vector Database
FAISS
Pinecone
Milvus
Qdrant

Python
Spark
Airflow

Learning To Rank
NDCG
MRR

Production ML

5-9 years experience
"""

In [359]:
jd_embedding = embedding_engine.encode_text(
    retrieval_query
)

print(
    jd_embedding.shape
)

(384,)

In [360]:
scores, indices = index.search(

    jd_embedding.reshape(
        1,
        -1
    ).astype(
        "float32"
    ),

    1000
)

print(
    len(
        indices[0]
    )
)

1000

In [361]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = (
        role_engine.score(
            candidate
        )
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = (
        signal_engine.score(
            candidate
        )
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = (
        ranker.score(

            semantic_score,

            role_score,

            evidence_score,

            signal_score,

            integrity_score
        )
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(
        ranked_candidates
    )
)

1000

In [362]:
top100 = ranked_candidates[:100]

print(
    len(
        top100
    )
)

100

In [363]:
candidate_ids = [

    row["candidate"][
        "candidate_id"
    ]

    for row in top100
]

print(
    "Unique:",
    len(
        set(
            candidate_ids
        )
    )
)

print(
    "Total:",
    len(
        candidate_ids
    )
)

Unique: 100
Total: 100

In [364]:
for row in top100[:20]:

    print(
        "=" * 80
    )

    print(
        row["candidate"][
            "candidate_id"
        ]
    )

    print(
        row["candidate"][
            "current_title"
        ]
    )

    print(
        row["final_score"]
    )

================================================================================
CAND_0000031
Recommendation Systems Engineer
290.06
================================================================================
CAND_0000665
Senior Software Engineer
286.34
================================================================================
CAND_0000666
Data Scientist
277.27
================================================================================
CAND_0000422
AI Research Engineer
274.5
================================================================================
CAND_0000874
Senior Software Engineer
265.75
================================================================================
CAND_0000852
Senior Software Engineer
259.4
================================================================================
CAND_0000775
Software Engineer
254.53
================================================================================
CAND_0000947
Analytics Engineer
253.52
================================================================================
CAND_0000584
Analytics Engineer
244.89
================================================================================
CAND_0000970
Data Engineer
240.56
================================================================================
CAND_0000878
Backend Engineer
240.36
================================================================================
CAND_0000165
AI Specialist
237.52
================================================================================
CAND_0000440
Software Engineer
236.76
================================================================================
CAND_0000969
AI Specialist
233.57
================================================================================
CAND_0000578
Data Engineer
226.52
================================================================================
CAND_0000273
ML Engineer
223.46
================================================================================
CAND_0000981
ML Engineer
222.33
================================================================================
CAND_0000210
Senior Data Engineer
220.72
================================================================================
CAND_0000820
Backend Engineer
216.03
================================================================================
CAND_0000705
AI Research Engineer
213.41

In [365]:
import pandas as pd

submission_df = pd.DataFrame([

    {

        "rank":
            i + 1,

        "candidate_id":
            row["candidate"][
                "candidate_id"
            ],

        "score":
            round(
                row["final_score"],
                2
            )
    }

    for i, row in enumerate(
        top100
    )
])

submission_df.head()

   rank  candidate_id   score
0     1  CAND_0000031  290.06
1     2  CAND_0000665  286.34
2     3  CAND_0000666  277.27
3     4  CAND_0000422  274.50
4     5  CAND_0000874  265.75

In [366]:
submission_df.to_csv(

    "top100_submission_final.csv",

    index=False
)

print(
    "Saved:",
    "top100_submission_final.csv"
)

Saved: top100_submission_final.csv

In [367]:
print(
    submission_df.shape
)

print(
    submission_df["candidate_id"].nunique()
)

print(
    submission_df["score"].describe()
)

(100, 3)
100
count    100.000000
mean     155.793500
std       60.717894
min       76.070000
25%       93.090000
50%      155.640000
75%      201.872500
max      290.060000
Name: score, dtype: float64

In [368]:
from collections import Counter

titles = [
    row["candidate"]["current_title"]
    for row in top100
]

for title, count in Counter(titles).most_common(30):
    print(title, count)

Software Engineer 24
Cloud Engineer 11
Full Stack Developer 9
Backend Engineer 8
Java Developer 7
DevOps Engineer 7
Analytics Engineer 6
Data Analyst 6
Senior Software Engineer 5
Data Engineer 5
AI Specialist 3
ML Engineer 3
AI Research Engineer 2
Senior Data Engineer 2
Recommendation Systems Engineer 1
Data Scientist 1

In [369]:
submission_df.head(20)

    rank  candidate_id   score
0      1  CAND_0000031  290.06
1      2  CAND_0000665  286.34
2      3  CAND_0000666  277.27
3      4  CAND_0000422  274.50
4      5  CAND_0000874  265.75
5      6  CAND_0000852  259.40
6      7  CAND_0000775  254.53
7      8  CAND_0000947  253.52
8      9  CAND_0000584  244.89
9     10  CAND_0000970  240.56
10    11  CAND_0000878  240.36
11    12  CAND_0000165  237.52
12    13  CAND_0000440  236.76
13    14  CAND_0000969  233.57
14    15  CAND_0000578  226.52
15    16  CAND_0000273  223.46
16    17  CAND_0000981  222.33
17    18  CAND_0000210  220.72
18    19  CAND_0000820  216.03
19    20  CAND_0000705  213.41

FINAL TEST ON ENTIRE DATASET

In [401]:
print("Candidates:", len(candidates))
print("Retrieved:", len(indices[0]))
print("Ranked:", len(ranked_candidates))
print("Top100:", len(top100))

Candidates: 100000
Retrieved: 1000
Ranked: 1000
Top100: 100

TIME OPTIMIZATION

In [402]:
from importlib import reload

import src.embeddings

reload(
    src.embeddings
)

from src.embeddings import (
    EmbeddingEngine
)

embedding_engine = (
    EmbeddingEngine()
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [382]:
candidate_embeddings = (

    embedding_engine.encode_candidates(

        candidates,

        batch_size=256
    )
)

candidate_embeddings = np.array(

    candidate_embeddings,

    dtype=np.float32
)

print(
    candidate_embeddings.shape
)

Batches:   0%|          | 0/391 [00:00<?, ?it/s]

(100000, 384)

In [403]:
np.save(
    "candidate_embeddings.npy",
    candidate_embeddings
)

In [404]:
candidate_embeddings.shape

(100000, 384)

In [405]:
import faiss
import numpy as np

dimension = candidate_embeddings.shape[1]

index = faiss.IndexFlatIP(
    dimension
)

index.add(
    candidate_embeddings
)

faiss.write_index(
    index,
    "candidate_index.faiss"
)

In [406]:
candidate_embeddings = np.load(
    "candidate_embeddings.npy"
)

index = faiss.read_index(
    "candidate_index.faiss"
)

In [407]:
import time

start = time.time()

jd_embedding = embedding_engine.encode_jd(
    parsed_jd
)

scores, indices = index.search(
    np.array(
        [jd_embedding],
        dtype=np.float32
    ),
    1000
)

print(
    "Retrieved:",
    len(indices[0])
)

print(
    "Time:",
    round(
        time.time() - start,
        3
    ),
    "sec"
)

Retrieved: 1000
Time: 0.061 sec

In [408]:
import time

start = time.time()

# COMPLETE FINAL PIPELINE

print(
    round(
        time.time() - start,
        2
    ),
    "seconds"
)

0.0 seconds

In [409]:
print(len(candidates))
print(len(ranked_candidates))
print(len(top100))
print(submission_df.shape)
print(submission_df["candidate_id"].nunique())

100000
1000
100
(100, 3)
100

In [410]:
import numpy as np
import faiss

candidate_embeddings = np.load(
    "candidate_embeddings.npy"
)

index = faiss.read_index(
    "candidate_index.faiss"
)

print(candidate_embeddings.shape)

(100000, 384)

In [411]:
jd_embedding = (
    embedding_engine.encode_jd(
        parsed_jd
    )
)

jd_embedding = np.array(
    [jd_embedding],
    dtype=np.float32
)

print(jd_embedding.shape)

(1, 384)

In [412]:
scores, indices = index.search(
    jd_embedding,
    1000
)

print(
    "Retrieved:",
    len(indices[0])
)

Retrieved: 1000

In [413]:
retrieved_candidates = [

    candidates[idx]

    for idx in indices[0]
]

print(
    len(retrieved_candidates)
)

1000

In [414]:
ranked_candidates = []

for rank_pos, idx in enumerate(
    indices[0]
):

    candidate = candidates[idx]

    semantic_score = float(
        scores[0][rank_pos]
    )

    role_score = role_engine.score(
        candidate
    )

    evidence_score = (
        evidence_engine.score(
            candidate
        )
    )

    signal_score = signal_engine.score(
        candidate
    )

    integrity_score = (
        integrity_engine.score(
            candidate
        )
    )

    final_score = ranker.score(

        semantic_score=
            semantic_score,

        role_score=
            role_score,

        evidence_score=
            evidence_score,

        signal_score=
            signal_score,

        integrity_score=
            integrity_score
    )

    ranked_candidates.append({

        "candidate":
            candidate,

        "semantic_score":
            semantic_score,

        "role_score":
            role_score,

        "evidence_score":
            evidence_score,

        "signal_score":
            signal_score,

        "integrity_score":
            integrity_score,

        "final_score":
            final_score
    })

print(
    len(ranked_candidates)
)

1000

In [415]:
ranked_candidates = sorted(

    ranked_candidates,

    key=lambda x:
        x["final_score"],

    reverse=True
)

print(
    len(ranked_candidates)
)

1000

In [416]:
top100 = ranked_candidates[:100]

print(
    len(top100)
)

100

In [417]:
submission_rows = []

for rank, item in enumerate(
    top100,
    start=1
):

    submission_rows.append({

        "rank":
            rank,

        "candidate_id":
            item["candidate"][
                "candidate_id"
            ],

        "score":
            round(
                item["final_score"],
                2
            )
    })

submission_df = pd.DataFrame(
    submission_rows
)

submission_df.head()

   rank  candidate_id   score
0     1  CAND_0055992  407.24
1     2  CAND_0079387  405.28
2     3  CAND_0005649  405.28
3     4  CAND_0044883  404.48
4     5  CAND_0069905  398.37

In [418]:
print(
    submission_df.shape
)

print(
    submission_df[
        "candidate_id"
    ].nunique()
)

submission_df.describe()

(100, 3)
100

             rank       score
count  100.000000  100.000000
mean    50.500000  324.808200
std     29.011492   35.540821
min      1.000000  282.160000
25%     25.750000  292.785000
50%     50.500000  317.360000
75%     75.250000  349.920000
max    100.000000  407.240000

In [421]:
submission_df.to_csv(

    "top100_submission.csv",

    index=False
)

print(
    "CSV Saved Successfully"
)

CSV Saved Successfully

In [420]:
import time

start = time.time()

candidate_embeddings = np.load(
    "candidate_embeddings.npy"
)

index = faiss.read_index(
    "candidate_index.faiss"
)

jd_embedding = (
    embedding_engine.encode_jd(
        parsed_jd
    )
)

jd_embedding = np.array(
    [jd_embedding],
    dtype=np.float32
)

scores, indices = index.search(
    jd_embedding,
    1000
)

retrieved_candidates = [
    candidates[idx]
    for idx in indices[0]
]

print(
    "Pipeline Time:",
    round(
        time.time() - start,
        2
    ),
    "seconds"
)

Pipeline Time: 0.2 seconds

In [422]:
submission_df.head()

   rank  candidate_id   score
0     1  CAND_0055992  407.24
1     2  CAND_0079387  405.28
2     3  CAND_0005649  405.28
3     4  CAND_0044883  404.48
4     5  CAND_0069905  398.37

In [423]:
submission_df.columns.tolist()

['rank', 'candidate_id', 'score']

In [424]:
submission_df.shape

(100, 3)

In [428]:
import os
print(os.getcwd())

d:\India Runs\TalentDNA_AI\notebooks

In [429]:
import pandas as pd

df = pd.read_csv("top100_submission_final.csv")

print(df.shape)
print(df.columns.tolist())

(100, 3)
['rank', 'candidate_id', 'score']

In [430]:
submission_df

    rank  candidate_id   score
0      1  CAND_0055992  407.24
1      2  CAND_0079387  405.28
2      3  CAND_0005649  405.28
3      4  CAND_0044883  404.48
4      5  CAND_0069905  398.37
..   ...           ...     ...
95    96  CAND_0061291  283.03
96    97  CAND_0047721  282.72
97    98  CAND_0073645  282.56
98    99  CAND_0002025  282.51
99   100  CAND_0039754  282.16

[100 rows x 3 columns]

In [446]:
from src.reason_generator import ReasonGenerator

reason_generator = ReasonGenerator()

In [447]:
submission_df

,rank,candidate_id,score,reasoning
0,1,CAND_0055992,407.24,16.9 years experience. background as AI Engine...
1,2,CAND_0079387,405.28,6.9 years experience. background as AI Enginee...
2,3,CAND_0005649,405.28,7.4 years experience. background as Senior Dat...
3,4,CAND_0044883,404.48,6.3 years experience. background as AI Enginee...
4,5,CAND_0069905,398.37,6.6 years experience. background as Applied ML...
...,...,...,...,...
95,96,CAND_0061291,283.03,6.9 years experience. background as Data Engin...
96,97,CAND_0047721,282.72,7.0 years experience. background as Senior Dat...
97,98,CAND_0073645,282.56,6.7 years experience. background as Data Engin...
98,99,CAND_0002025,282.51,5.9 years experience. background as Senior AI ...
99,100,CAND_0039754,282.16,16.2 years experience. background as Senior Ap...

In [448]:
print(top100[0].keys())

dict_keys(['candidate', 'semantic_score', 'role_score', 'evidence_score', 'signal_score', 'integrity_score', 'final_score'])

In [450]:
submission_df = submission_df[
    [
        "candidate_id",
        "rank",
        "score",
        "reasoning"
    ]
]

submission_df.to_csv(
    "top100_submission_final.csv",
    index=False
)

In [451]:
submission_df.to_csv(
    "top100_submission_final.csv",
    index=False
)